apiVersion: chaos-mesh.org/v1alpha1
kind: DNSChaos
metadata:
  name: dns-block-cartservice
  namespace: chaos-testing
spec:
  action: error
  mode: all
  selector:
    namespaces:
    - online-boutique-research
    labelSelectors:
      app: cartservice
  patterns:
  - '*'
  duration: 60s
