apiVersion: chaos-mesh.org/v1alpha1
kind: DNSChaos
metadata:
  name: kubernetes-dns-chaos
  namespace: chaos-mesh
  labels:
    experiment-type: infrastructure
    target-service: kubernetes-api
    severity: high
spec:
  action: error
  mode: fixed
  value: '1'
  duration: 5m
  selector:
    namespaces:
    - observability
    labelSelectors:
      app.kubernetes.io/name: kube-prometheus-stack-prometheus
  patterns:
  - kubernetes.default.svc.cluster.local
  scheduler:
    cron: 0 17 * * THU
