apiVersion: chaos-mesh.org/v1alpha1
kind: DNSChaos
metadata:
  name: kafka-app-dns-error
  namespace: kafka-producer
spec:
  action: error
  mode: all
  selector:
    namespaces:
    - kafka-producer
    labelSelectors:
      app.kubernetes.io/name: kafka-producer
  patterns:
  - kafka-cluster-kafka-bootstrap.kafka-cluster*
  - schema-registry.schema-registry*
  duration: 1m
