apiVersion: chaos-mesh.org/v1alpha1
kind: DNSChaos
metadata:
  name: vernemq-dns-chaos
  namespace: chaos-mesh
  labels:
    experiment-type: infrastructure
    target-service: vernemq
    severity: high
    storage.samcloud.online/tier: standard
spec:
  action: error
  mode: fixed
  value: '1'
  duration: 10m
  selector:
    namespaces:
    - storage
    labelSelectors:
      app.kubernetes.io/name: vernemq
  patterns:
  - vernemq-*.storage.svc.cluster.local
  - '*.storage.svc.cluster.local'
  scheduler:
    cron: 0 17 * * THU
