apiVersion: chaos-mesh.org/v1alpha1
kind: DNSChaos
metadata:
  name: dns-error
  namespace: mesh-system
spec:
  action: error
  mode: fixed-percent
  value: '10'
  selector:
    namespaces:
    - mesh-system
  patterns:
  - '*.mesh-system.svc.cluster.local'
  duration: 30s
