apiVersion: chaos-mesh.org/v1alpha1
kind: DNSChaos
metadata:
  name: dns-spoofing-experiment
  namespace: chaos-demo
spec:
  mode: all
  selector:
    namespaces:
    - chaos-demo
    labelSelectors:
      app: frontend
  action: replace
  patterns:
  - backend
  records:
  - name: backend
    recordType: A
    data: 10.0.0.1
  duration: 3m
