apiVersion: chaos-mesh.org/v1alpha1
kind: DNSChaos
metadata:
  name: api-keycloak-dns
  namespace: sentinelrag-chaos
spec:
  action: error
  mode: all
  selector:
    namespaces:
    - sentinelrag
    labelSelectors:
      app.kubernetes.io/component: api
      app.kubernetes.io/part-of: sentinelrag
  patterns:
  - auth.dev.sentinelrag.example.com
  duration: 5m
