apiVersion: chaos-mesh.org/v1alpha1
kind: DNSChaos
metadata:
  name: dns-chaos
  namespace: chaos-testing
  labels:
    app.kubernetes.io/part-of: chaos-engineering-toolkit
    experiment: dns-chaos
spec:
  action: error
  mode: one
  selector:
    namespaces:
    - default
    labelSelectors:
      app: target-service
  patterns:
  - api.example.com
  - '*.internal.example.com'
  duration: 3m
