apiVersion: chaos-mesh.org/v1alpha1
kind: DNSChaos
metadata:
  name: dns-chaos-test
  namespace: chaos-testing
spec:
  action: error
  mode: all
  selector:
    namespaces:
    - self-healing-prod
    labelSelectors:
      app: gateway-service
  patterns:
  - auth-service.*
  duration: 2m
