apiVersion: chaos-mesh.org/v1alpha1
kind: DNSChaos
metadata:
  name: dns-random-experiment
  namespace: chaos-demo
spec:
  mode: all
  selector:
    namespaces:
    - chaos-demo
    labelSelectors:
      app: frontend
  action: random
  duration: 2m
