apiVersion: chaos-mesh.org/v1alpha1
kind: DNSChaos
metadata:
  name: dns-latency-experiment
  namespace: chaos-demo
spec:
  mode: all
  selector:
    namespaces:
    - chaos-demo
    labelSelectors:
      app: frontend
  action: delay
  delay: 5
  duration: 3m
