apiVersion: chaos-mesh.org/v1alpha1
kind: DNSChaos
metadata:
  name: dns-random-notification
  namespace: chaos-testing
  labels:
    experiment: dns-chaos
    tier: advanced
    app.kubernetes.io/part-of: self-healing-infra
  annotations:
    chaos.selfhealing.io/description: Random DNS responses for notification-service
spec:
  action: random
  mode: all
  selector:
    namespaces:
    - self-healing
    labelSelectors:
      app.kubernetes.io/name: notification-service
  duration: 60s
  patterns:
  - '*.self-healing.svc.cluster.local'
