apiVersion: chaos-mesh.org/v1alpha1
kind: DNSChaos
metadata:
  name: dns-failure
  namespace: chaos-testing
spec:
  action: error
  mode: random-max-percent
  value: '25'
  duration: 5m
  selector:
    namespaces:
    - skalean-system
  patterns:
  - postgres-primary
  - redis-primary
  scheduler:
    cron: '@every 3h'
