apiVersion: chaos-mesh.org/v1alpha1
kind: AWSChaos
metadata:
  name: ec2-stop
  namespace: chaos-testing
spec:
  action: ec2-stop
  duration: 10m
  awsRegion: ca-west-1
  ec2Instance: i-1234567890abcdef0
  secretName: aws-credentials
  scheduler:
    cron: '@every 24h'
