apiVersion: chaos-mesh.org/v1alpha1
kind: JVMChaos
metadata:
  name: kafka-jvm-gc
  namespace: kafka-cluster
spec:
  action: gc
  mode: one
  selector:
    namespaces:
    - kafka-cluster
    labelSelectors:
      strimzi.io/cluster: kafka-cluster
      strimzi.io/kind: Kafka
  duration: 30s
