apiVersion: chaos-mesh.org/v1alpha1
kind: JVMChaos
metadata:
  name: kafka-jvm-method-latency
  namespace: kafka-cluster
spec:
  action: latency
  mode: one
  selector:
    namespaces:
    - kafka-cluster
    labelSelectors:
      strimzi.io/cluster: kafka-cluster
      strimzi.io/kind: Kafka
  class: kafka.log.UnifiedLog
  method: append
  latency: 500
  duration: 1m
