apiVersion: chaos-mesh.org/v1alpha1
kind: JVMChaos
metadata:
  name: kafka-jvm-memory-stress
  namespace: kafka-cluster
spec:
  action: stress
  mode: one
  selector:
    namespaces:
    - kafka-cluster
    labelSelectors:
      strimzi.io/cluster: kafka-cluster
      strimzi.io/kind: Kafka
  memType: heap
  duration: 1m
