apiVersion: chaos-mesh.org/v1alpha1
kind: JVMChaos
metadata:
  name: exception
  namespace: mysql
spec:
  action: mysql
  mysqlConnectorVersion: '8'
  database: mysql
  table: user
  exception: BOOM
  mode: all
  selector:
    labelSelectors:
      app: mysql-query
