apiVersion: chaos-mesh.org/v1alpha1
kind: TimeChaos
metadata:
  name: provider-clock-skew
  namespace: chaos-testing
  labels:
    chaos.virtengine.com/category: time
    chaos.virtengine.com/scenario: provider
spec:
  mode: all
  selector:
    namespaces:
    - virtengine
    labelSelectors:
      app.kubernetes.io/component: provider-daemon
  timeOffset: 15m
  duration: 180s
