apiVersion: chaos-mesh.org/v1alpha1
kind: TimeChaos
metadata:
  name: aiflow-time-skew
  namespace: agents-staging
spec:
  mode: one
  selector:
    namespaces:
    - agents-staging
    labelSelectors:
      app: aiflow-social-agent
  timeOffset: -10m
  duration: 1m
