apiVersion: chaos-mesh.org/v1alpha1
kind: TimeChaos
metadata:
  name: time-shift
  namespace: chaos-mesh
spec:
  mode: one
  selector:
    namespaces:
    - podinfo
    labelSelectors:
      app.kubernetes.io/name: podinfo
  timeOffset: -10m100ns
  clockIds:
  - CLOCK_REALTIME
  containerNames:
  - pd
  duration: 10s
  scheduler:
    cron: '@every 15s'
