apiVersion: chaos-mesh.org/v1alpha1
kind: TimeChaos
metadata:
  name: time-skew-backward-chaos
  namespace: staging
  labels:
    app.kubernetes.io/part-of: gp-chaos-engineering
spec:
  mode: all
  selector:
    namespaces:
    - staging
    labelSelectors:
      app.kubernetes.io/part-of: my-app
  timeOffset: -1h
  duration: 120s
