apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: front-end-network-delay
  namespace: chaos-testing
spec:
  action: delay
  mode: one
  selector:
    namespaces:
    - sock-shop
    labelSelectors:
      app: front-end
  delay:
    latency: 2000ms
    correlation: '100'
    jitter: 0ms
  duration: 2m
  scheduler:
    cron: '@once'
