apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: db-network-latency
  namespace: chaos-testing
spec:
  action: delay
  mode: all
  selector:
    namespaces:
    - default
    labelSelectors:
      app: postgres
  delay:
    latency: 100ms
    correlation: '100'
    jitter: 0ms
  duration: 60s
  scheduler:
    cron: '@every 15m'
