apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-partition-amf-nrf
  namespace: open5gs
spec:
  action: partition
  mode: all
  selector:
    namespaces:
    - open5gs
    labelSelectors:
      app.kubernetes.io/name: amf
      app.kubernetes.io/instance: open5gs
  direction: both
  target:
    mode: all
    selector:
      namespaces:
      - open5gs
      labelSelectors:
        app.kubernetes.io/name: scp
        app.kubernetes.io/instance: open5gs
  duration: 5m
