apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: scenario-e-network
  namespace: chaos-testing
  labels:
    experiment: scenario-e
spec:
  action: delay
  mode: all
  selector:
    namespaces:
    - online-boutique
    labelSelectors:
      app: productcatalogservice
  delay:
    latency: 500ms
    jitter: 200ms
    correlation: '25'
  direction: to
  duration: 10m
