kind: NetworkChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace:
    namespace: null
  name:
    name: null
spec:
  selector:
    namespaces:
    - namespace: null
    labelSelectors:
      app:
        app: null
    pods:
      default:
        pods: null
  mode: all
  action: loss
  duration:
    duration: null
  loss:
    loss: '{loss}'
    correlation: '{correlation}'
  direction: to
  target:
    selector:
      namespaces:
      - namespace: null
      labelSelectors:
        app:
          targetapp: null
      pods:
        default:
        - targetpods: null
    mode: all
