apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: bandwidth-limit-test
  namespace: chaos-system
  labels:
    app: chaos-experiment
    scenario: basic-resilience
spec:
  action: bandwidth
  mode: one
  duration: 10m
  scheduler:
    cron: 0 18 * * 3
  selector:
    namespaces:
    - pake-system
    labelSelectors:
      app: pake-api
    expressionSelectors:
    - key: chaos-test
      operator: In
      values:
      - enabled
  bandwidth:
    rate: 10mbps
    limit: 1024
    buffer: 1024
