apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: pesitwizard-network-partition
  namespace: staging
  labels:
    app: pesitwizard
    chaos-type: network-partition
spec:
  action: partition
  mode: all
  selector:
    namespaces:
    - staging
    labelSelectors:
      app: pesitwizard-server
  direction: both
  target:
    mode: one
    selector:
      namespaces:
      - staging
      labelSelectors:
        app: pesitwizard-server
  duration: 30s
