apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: securerag-network-partition
  namespace: securerag-hub
  annotations:
    feature.securerag.dev/enable-chaos-mesh: 'true'
    chaos.securerag.dev/category: network
spec:
  action: partition
  mode: one
  selector:
    namespaces:
    - securerag-hub
    labelSelectors:
      app.kubernetes.io/name: chatbot-manager
  direction: both
  scheduler:
    cron: '@every 2h'
  duration: 10s
