apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: database-error-experiment
  namespace: selfhealing
spec:
  action: loss
  mode: one
  selector:
    namespaces:
    - selfhealing
    labelSelectors:
      app: crave-backend
  direction: to
  target:
    mode: one
    selector:
      namespaces:
      - selfhealing
      labelSelectors:
        app: crave-postgres
  loss:
    loss: '100'
    correlation: '100'
  duration: 3m
