apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: remote-nginx-delay
  namespace: chaos-demo
spec:
  remoteCluster: remote-cluster-1
  action: delay
  mode: fixed-percent
  value: '50'
  selector:
    namespaces:
    - chaos-demo
    labelSelectors:
      app: nginx-demo
  delay:
    latency: 120ms
    correlation: '25'
    jitter: 30ms
  duration: 60s
