apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: pesitwizard-network-latency
  namespace: staging
  labels:
    app: pesitwizard
    chaos-type: network-delay
spec:
  action: delay
  mode: all
  selector:
    namespaces:
    - staging
    labelSelectors:
      app: pesitwizard-server
  delay:
    latency: 500ms
    correlation: '50'
    jitter: 100ms
  duration: 5m
  scheduler:
    cron: 30 */4 * * *
