apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: model-service-blackhole
  namespace: stage10
spec:
  action: loss
  mode: all
  selector:
    namespaces:
    - stage10
    labelSelectors:
      app: decision-engine
  loss:
    loss: '100'
    correlation: '0'
  duration: 2m
  direction: to
  target:
    selector:
      namespaces:
      - stage9c
      labelSelectors:
        app: model-service
  scheduler:
    cron: '@every 1h'
