apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-delay-right-leg
spec:
  action: delay
  direction: to
  mode: one
  selector:
    labelSelectors:
      component: podtato-head-right-leg
  target:
    mode: all
    selector:
      labelSelectors:
        component: podtato-head-entry
  delay:
    latency: 800ms
    correlation: '100'
    jitter: 0ms
