apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: wordscom-latency-chaos
  namespace: wordscom-production
spec:
  action: delay
  mode: all
  selector:
    labelSelectors:
      app: wordscom
  delay:
    latency: 100ms
    correlation: '50'
    jitter: 30ms
  duration: 60s
