apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-loss-experiment
  namespace: qbitel
spec:
  action: loss
  mode: one
  selector:
    namespaces:
    - qbitel
    labelSelectors:
      app: qbitel
  loss:
    loss: '25'
    correlation: '25'
  duration: 2m
  direction: to
