apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: kafka-network-latency-all-3
  namespace: myproject
spec:
  action: delay
  mode: all
  selector:
    labelSelectors:
      strimzi.io/kind: Kafka
  delay:
    latency: 100ms
    jitter: 3ms
  duration: 5m
