apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: remitflow-tigerbeetle-packet-loss
  namespace: remitflow-staging
  labels:
    app.kubernetes.io/part-of: remitflow
    chaos-type: network
    target: tigerbeetle
spec:
  action: loss
  mode: one
  selector:
    namespaces:
    - remitflow-staging
    labelSelectors:
      app: tigerbeetle
  loss:
    loss: '10'
    correlation: '25'
  duration: 2m
