apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: brain-storm-network-partition
  namespace: default
spec:
  action: partition
  mode: all
  selector:
    namespaces:
    - default
    labelSelectors:
      app: brain-storm-backend
  direction: both
  duration: 3m
  scheduler:
    cron: '@daily'
