apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-delay-test
  namespace: estatewise
spec:
  action: delay
  mode: one
  selector:
    namespaces:
    - estatewise
    labelSelectors:
      app: estatewise-backend
  delay:
    latency: 500ms
    correlation: '50'
    jitter: 100ms
  duration: 2m
