apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: db-network-latency
  namespace: conductor-prod
spec:
  action: delay
  mode: all
  selector:
    labelSelectors:
      app: postgres-db
  delay:
    latency: 500ms
    correlation: '100'
    jitter: 0ms
  duration: 3m
  scheduler:
    cron: '@every 30m'
