apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-loss-test
  namespace: chaos-testing
  labels:
    experiment: resilience
    type: network-loss
spec:
  action: loss
  mode: all
  selector:
    namespaces:
    - app-team-a-dev
    labelSelectors:
      app: api-gateway
  loss:
    loss: '10'
    correlation: '25'
  direction: both
  duration: 3m
