apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: partition-50pct
  namespace: mesh-system
spec:
  action: partition
  mode: fixed-percent
  value: '50'
  selector:
    namespaces:
    - mesh-system
    labelSelectors:
      app.kubernetes.io/component: mesh-node
  direction: both
  duration: 30s
