apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: solo-chaos-network-netem-ap-to-eu
  namespace: chaos-mesh
spec:
  action: netem
  mode: all
  selector:
    namespaces:
    - ${NAMESPACE}
    labelSelectors:
      solo.hedera.com/type: network-node
      solo.hedera.com/region: ap
  target:
    mode: all
    selector:
      namespaces:
      - ${NAMESPACE}
      labelSelectors:
        solo.hedera.com/type: network-node
        solo.hedera.com/region: eu
  delay:
    latency: 150ms
    correlation: '80'
    jitter: 30ms
  rate:
    rate: 1gbps
