apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-loss-experiment
  namespace: estatewise
spec:
  action: loss
  mode: one
  selector:
    namespaces:
    - estatewise
    labelSelectors:
      app: backend
  loss:
    loss: '10'
    correlation: '50'
  duration: 30s
  scheduler:
    cron: '@weekly'
