apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: solo-chaos-network-partition-${UUID}
  namespace: chaos-mesh
spec:
  action: partition
  mode: all
  selector:
    namespaces:
    - ${NAMESPACE}
    labelSelectors:
      solo.hedera.com/type: network-node
      solo.hedera.com/region: ${SOURCE_REGION}
  direction: both
  target:
    mode: all
    selector:
      namespaces:
      - ${NAMESPACE}
      labelSelectors:
        solo.hedera.com/type: network-node
        solo.hedera.com/region: ${TARGET_REGION}
