apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: external-api-delay
  namespace: security-monitor
spec:
  action: delay
  mode: all
  selector:
    namespaces:
    - security-monitor
    labelSelectors:
      app: security-monitor
  delay:
    latency: 2s
    correlation: '100'
  duration: 10m
  direction: to
  externalTargets:
  - api.abuseipdb.com
  - api.virustotal.com
  - api.shodan.io
