apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-delay
  namespace: security-monitor
spec:
  action: delay
  mode: one
  selector:
    namespaces:
    - security-monitor
    labelSelectors:
      app: security-monitor
  delay:
    latency: 100ms
    correlation: '25'
    jitter: 10ms
  duration: 5m
  direction: to
  target:
    mode: all
    selector:
      namespaces:
      - security-monitor
