apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: cosmic-network-delay
  namespace: load-testing
spec:
  action: delay
  mode: all
  selector:
    namespaces:
    - terrafusion-cosmic
    labelSelectors:
      app: cosmic-orchestrator
  delay:
    latency: 100ms
    correlation: '50'
    jitter: 50ms
  duration: 5m
  scheduler:
    cron: '@every 2h'
