apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: duplicate-packets-test
  namespace: chaos-engineering
  labels:
    experiment-type: duplicate
    target-service: auth-service
    severity: low
    automation: enabled
spec:
  action: duplicate
  mode: one
  selector:
    namespaces:
    - rust-security-dev
    labelSelectors:
      app: auth-service
  duplicate:
    duplicate: 25%
    correlation: '25'
  duration: 3m
  scheduler:
    cron: 0 5 * * 4
