apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: redis-delay
  namespace: llmchat
spec:
  action: delay
  mode: all
  selector:
    namespaces:
    - llmchat
    labelSelectors:
      app: redis
  delay:
    latency: 50ms
    correlation: '100'
    jitter: 5ms
  duration: 5m
