apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-delay-test
  namespace: chaos-system
  labels:
    app: chaos-experiment
    scenario: basic-resilience
spec:
  action: delay
  mode: one
  duration: 10m
  scheduler:
    cron: 0 17 * * 2
  selector:
    namespaces:
    - pake-system
    labelSelectors:
      app: pake-workers-high
    expressionSelectors:
    - key: chaos-test
      operator: In
      values:
      - enabled
  delay:
    latency: 100ms
    correlation: '100'
    jitter: 10ms
