apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: data-plane-network-partition
  namespace: govsecure
spec:
  action: partition
  mode: one
  selector:
    namespaces:
    - govsecure
    labelSelectors:
      app: data-plane
  direction: to
  target:
    mode: one
    selector:
      namespaces:
      - govsecure
      labelSelectors:
        app: audit-service
  duration: 30s
  scheduler:
    cron: '@every 12h'
