apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: kafka-packet-loss
  namespace: chaos-mesh
  labels:
    experiment: packet-loss
spec:
  action: loss
  mode: all
  selector:
    namespaces:
    - employee-platform
    labelSelectors:
      app: notification-service
  loss:
    loss: '20'
    correlation: '25'
  target:
    selector:
      namespaces:
      - employee-platform
      labelSelectors:
        app: kafka
    mode: all
  duration: 1m
