apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-loss-echo-server
  namespace: echo-server
  labels:
    app.kubernetes.io/part-of: chaos-engineering
    experiment: network-loss
spec:
  action: loss
  mode: all
  selector:
    namespaces:
    - echo-server
    labelSelectors:
      app: echo-server
  loss:
    loss: '50'
    correlation: '25'
  direction: to
  target:
    mode: all
    selector:
      namespaces:
      - services
      labelSelectors:
        app.kubernetes.io/name: redis
  duration: 120s
