apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: net-latency-task-api
  namespace: chaos-testing
spec:
  action: delay
  mode: all
  selector:
    namespaces:
    - svc-task
    labelSelectors:
      app: task-api
  delay:
    latency: 100ms
    jitter: 10ms
    correlation: '0'
  direction: to
  duration: 30s
