apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: epic8-bandwidth-limitation-test
  namespace: epic8-prod
  labels:
    epic8.platform/experiment: bandwidth-limitation
    epic8.platform/component: chaos-engineering
spec:
  action: bandwidth
  mode: fixed
  value: '1'
  duration: 360s
  bandwidth:
    rate: 10mbps
    limit: 20971520
    buffer: 10000
  direction: both
  selector:
    namespaces:
    - epic8-prod
    labelSelectors:
      epic8.platform/service: analytics
