apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: service-a-v2-packet-loss
  namespace: canary-playground
spec:
  action: loss
  mode: all
  selector:
    labelSelectors:
      app: service-a
      version: v2
  loss:
    loss: '20'
    correlation: '30'
  duration: 1m
  scheduler:
    cron: 15 */1 * * *
