apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: kafka-consumer-partition
  namespace: ai-testops
spec:
  action: partition
  mode: all
  selector:
    namespaces:
    - ai-testops
    labelSelectors:
      app: test-execute-consumer
  direction: to
  target:
    mode: all
    selector:
      namespaces:
      - ai-testops
      labelSelectors:
        app: kafka
  duration: 30s
