apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: remitflow-redis-partition
  namespace: remitflow-staging
  labels:
    app.kubernetes.io/part-of: remitflow
    chaos-type: network
    target: redis
spec:
  action: partition
  mode: one
  selector:
    namespaces:
    - remitflow-staging
    labelSelectors:
      app: redis
  direction: both
  target:
    mode: one
    selector:
      namespaces:
      - remitflow-staging
      labelSelectors:
        app: remitflow-server
  duration: 2m
