apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: dns-failure
  namespace: security-monitor
spec:
  action: delay
  mode: all
  selector:
    namespaces:
    - security-monitor
    labelSelectors:
      app: security-monitor
  delay:
    latency: 5s
  duration: 3m
  direction: to
  target:
    mode: all
    selector:
      namespaces:
      - kube-system
      labelSelectors:
        k8s-app: kube-dns
