apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: remitflow-kafka-latency
  namespace: remitflow-staging
  labels:
    app.kubernetes.io/part-of: remitflow
    chaos-type: network
    target: kafka
spec:
  action: delay
  mode: one
  selector:
    namespaces:
    - remitflow-staging
    labelSelectors:
      app: kafka
  delay:
    latency: 200ms
    correlation: '25'
    jitter: 50ms
  duration: 5m
  scheduler:
    cron: '@every 1h'
