apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-latency
  namespace: chaos-testing
spec:
  action: delay
  mode: random-max-percent
  value: '50'
  duration: 15m
  selector:
    namespaces:
    - skalean-system
  delay:
    latency: 500ms
    correlation: '50'
    jitter: 100ms
  scheduler:
    cron: '@every 45m'
