apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: snapshot-controller-network-delay
  namespace: storage
  labels:
    app.kubernetes.io/name: snapshot-controller
    app.kubernetes.io/component: chaos-testing
spec:
  action: delay
  mode: one
  selector:
    namespaces:
    - storage
    labelSelectors:
      app.kubernetes.io/name: snapshot-controller
  delay:
    latency: 100ms
    correlation: '100'
    jitter: 0ms
  duration: 5m
  scheduler:
    cron: '@every 24h'
