apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  namespace: his-hope
  name: partition-identity-from-redis
  labels:
    app.kubernetes.io/part-of: his-hope
    chaos-mesh/experiment-type: network-partition
    chaos-mesh/schedule: routine
  annotations:
    description: Partitions identity-service from Redis every 12 hours to test session
      cache miss handling and fallback to database
    maintainer: his-hope-sre@hishop.com
spec:
  action: partition
  mode: all
  selector:
    namespaces:
    - his-hope
    labelSelectors:
      app: identity-service
  direction: both
  target:
    mode: all
    selector:
      namespaces:
      - his-hope
      labelSelectors:
        app.kubernetes.io/name: redis
  duration: 30s
  scheduler:
    cron: '@every 12h'
