apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: redis-connection-loss
  namespace: security-monitor
spec:
  action: loss
  mode: all
  selector:
    namespaces:
    - security-monitor
    labelSelectors:
      app: security-monitor
  loss:
    loss: '50'
  duration: 2m
  direction: both
  target:
    mode: all
    selector:
      namespaces:
      - security-monitor
      labelSelectors:
        app: redis
