apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: sp-api-memory-stress
  namespace: spatialpipe
spec:
  mode: one
  selector:
    namespaces:
    - spatialpipe
    labelSelectors:
      app.kubernetes.io/component: api
  stressors:
    memory:
      workers: 2
      size: 512MB
  duration: 60s
