apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: stress-database-cpu
  namespace: rca-sandbox
  labels:
    experiment: stress-cpu
    project: rca-research
spec:
  mode: all
  selector:
    namespaces:
    - rca-sandbox
    labelSelectors:
      app: database
  stressors:
    cpu:
      workers: 4
      load: 100
  duration: 3m
