apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: worker-cpu-stress
  namespace: chaos-testing
spec:
  mode: one
  selector:
    namespaces:
    - default
    labelSelectors:
      app: predator-worker
  stressors:
    cpu:
      workers: 1
      load: 100
  duration: 60s
  scheduler:
    cron: '@every 20m'
