apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: cpu-stress
  namespace: chaos-demo
spec:
  mode: one
  selector:
    namespaces:
    - chaos-demo
    labelSelectors:
      app: chaos-service
  stressors:
    cpu:
      workers: 4
      load: 90
  duration: 3m
