apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: cpu-stress-go-api
  namespace: go-api
  labels:
    app.kubernetes.io/part-of: chaos-engineering
    experiment: cpu-stress
spec:
  mode: one
  selector:
    namespaces:
    - go-api
    labelSelectors:
      app: go-api
  stressors:
    cpu:
      workers: 2
      load: 80
  duration: 120s
