apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: aiflow-cpu-stress
  namespace: agents-staging
spec:
  mode: one
  selector:
    namespaces:
    - agents-staging
    labelSelectors:
      app: aiflow-social-agent
  stressors:
    cpu:
      workers: 2
      load: 80
  duration: 3m
