apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: m15-s2-recommendation-noise
  namespace: techx-tf3
spec:
  mode: all
  duration: 5m
  selector:
    namespaces:
    - techx-tf3
    labelSelectors:
      app.kubernetes.io/name: recommendation
  containerNames:
  - recommendation
  stressors:
    cpu:
      workers: 1
      load: 20
