apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: cpu-stress-chaos
spec:
  mode: one
  selector:
    labelSelectors:
      security-test: enabled
  stressors:
    cpu:
      workers: 1
      load: 50
  duration: 30s
