apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: notification-service-memory-stress
spec:
  mode: one
  selector:
    labelSelectors:
      app: notification-service
    namespaces:
    - microservices
  duration: 120s
  stressors:
    memory:
      workers: 4
      size: 90%
