apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: mesh-memory-stress
  namespace: x0tta6bl4
  labels:
    scenario: memory-stress
spec:
  mode: fixed
  value: '2'
  selector:
    namespaces:
    - x0tta6bl4
    labelSelectors:
      app.kubernetes.io/name: x0tta6bl4
  stressors:
    memory:
      workers: 1
      size: 256MB
  duration: 120s
