apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: cpu-stress-test
  namespace: chaos-testing
spec:
  mode: one
  selector:
    namespaces:
    - default
    labelSelectors:
      app: new-pos
  stressors:
    cpu:
      workers: 4
      load: 80
  duration: 5m
