apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: combined-stress
  namespace: chaos-demo
spec:
  mode: one
  selector:
    namespaces:
    - chaos-demo
    labelSelectors:
      app: backend
  stressors:
    cpu:
      workers: 1
      load: 50
    memory:
      workers: 1
      size: 50Mi
  duration: 5m
