apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: brain-storm-cpu-stress
  namespace: default
spec:
  action: stress
  mode: all
  selector:
    namespaces:
    - default
    labelSelectors:
      app: brain-storm-backend
  stressors:
    cpu:
      workers: 2
      load: 80
  duration: 5m
  scheduler:
    cron: 0 4 * * *
