apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: cpu-stress
  namespace: chaos-testing
spec:
  mode: one
  selector:
    namespaces:
    - production
    labelSelectors:
      app: ergo-web
  stressors:
    cpu:
      workers: 2
      load: 80
  duration: 3m
