apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: securerag-cpu-stress
  namespace: securerag-hub
  annotations:
    feature.securerag.dev/enable-chaos-mesh: 'true'
    chaos.securerag.dev/category: resource
spec:
  mode: one
  selector:
    namespaces:
    - securerag-hub
    labelSelectors:
      app.kubernetes.io/name: portal-web
  stressors:
    cpu:
      workers: 1
      load: 50
  duration: 60s
