apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: memory-pressure-amf
  namespace: open5gs
spec:
  mode: all
  selector:
    namespaces:
    - open5gs
    labelSelectors:
      app.kubernetes.io/name: amf
      app.kubernetes.io/instance: open5gs
  stressors:
    memory:
      workers: 2
      size: 192MiB
  duration: 5m
