kind: StressChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: store
  name: checkoutservice-cpu-load
  annotations:
    experiment.chaos-mesh.org/pause: 'true'
spec:
  selector:
    namespaces:
    - store
    labelSelectors:
      app: checkoutservice
  mode: all
  stressors:
    cpu:
      workers: 1
      load: 100
