apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: stress-chaos-node
  namespace: kafka
spec:
  mode: all
  selector:
    namespaces:
    - kafka
    labelSelectors:
      strimzi.io/name: hacobot-kafka-kafka
  stressors:
    cpu:
      workers: 2
      load: 80
    memory:
      workers: 1
      size: 256MB
  duration: 120s
