apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: openstack-cpu-stress
  namespace: chaos-engineering
  labels:
    experiment: cpu-stress
    service: nova-compute
spec:
  mode: one
  selector:
    namespaces:
    - openstack-blue
    - openstack-green
    labelSelectors:
      component: compute
  stressors:
    cpu:
      workers: 2
      load: 80
    memory:
      workers: 1
      size: 1GB
  duration: 10m
  scheduler:
    cron: 0 5 * * 4
