apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: email-worker-cpu-stress
  namespace: reliability-lab
spec:
  mode: all
  selector:
    namespaces:
    - reliability-lab
    labelSelectors:
      app: email-worker
  stressors:
    cpu:
      workers: 2
      load: 95
  duration: 6m
