apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: memory-stress-echo-server
  namespace: echo-server
  labels:
    app.kubernetes.io/part-of: chaos-engineering
    experiment: memory-stress
spec:
  mode: one
  selector:
    namespaces:
    - echo-server
    labelSelectors:
      app: echo-server
  stressors:
    memory:
      workers: 1
      size: 200Mi
  duration: 120s
