apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: memory-stress-low
  namespace: default
spec:
  mode: all
  duration: 3m
  selector:
    namespaces:
    - default
    labelSelectors:
      app: demo
  stressors:
    memory:
      workers: 4
      size: 500MB
