apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: inventory-cpu-stress
  namespace: apps
  labels:
    experiment: cpu-stress
    service: inventory-service
spec:
  mode: all
  selector:
    namespaces:
    - apps
    labelSelectors:
      app: inventory-service
  stressors:
    cpu:
      workers: 2
      load: 90
  duration: 120s
