apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: memory-stress-test
  namespace: chaos-testing
spec:
  mode: fixed
  value: '1'
  selector:
    namespaces:
    - self-healing-prod
    labelSelectors:
      app: data-service
  stressors:
    memory:
      workers: 4
      size: 512Mi
  duration: 5m
  scheduler:
    cron: '@every 35m'
