apiVersion: chaos-mesh.org/v1alpha1
kind: BlockChaos
metadata:
  name: oscp-aws-block
  namespace: oscp-prod
spec:
  action: block
  mode: fixed-pod
  selector:
    namespaces:
    - oscp-prod
    labelSelectors:
      app.kubernetes.io/component: aws-scanner
  ioPercent: 90
  fillPercent: 80
  target:
    volumeNames:
    - /var/lib/s3-scanner
  duration: 120s
