apiVersion: chaos-mesh.org/v1alpha1
kind: IOChaos
metadata:
  name: io-latency-experiment
  namespace: chaos-demo
spec:
  action: latency
  mode: all
  selector:
    namespaces:
    - chaos-demo
    labelSelectors:
      app: backend
  volumePath: /app
  delay: 100ms
  percent: 50
  duration: 3m
