apiVersion: chaos-mesh.org/v1alpha1
kind: IOChaos
metadata:
  name: sentiment-io-delay
  namespace: default
spec:
  action: latency
  mode: one
  selector:
    namespaces:
    - default
    labelSelectors:
      app.kubernetes.io/name: mlops-sentiment
  volumePath: /app/model_cache
  path: '**/*'
  delay: 100ms
  percent: 50
  duration: 3m
  scheduler:
    cron: '@every 4h'
