apiVersion: chaos-mesh.org/v1alpha1
kind: IOChaos
metadata:
  name: disk-read-fault
  namespace: backend
spec:
  action: fault
  mode: fixed-percent
  value: '50'
  selector:
    namespaces:
    - backend
    labelSelectors:
      chaos-target: 'true'
  volumePath: /mnt/chaos
  path: /mnt/chaos/*
  errno: 5
  percent: 100
  methods:
  - READ
  duration: 20m
