apiVersion: chaos-mesh.org/v1alpha1
kind: IOChaos
metadata:
  name: readonly-fs
  namespace: chaos-testing
spec:
  action: errno
  mode: one
  selector:
    namespaces:
    - llm-marketplace
  volumePath: /var/lib/data
  path: /var/lib/data/**/*
  errno: 30
  percent: 100
  methods:
  - write
  duration: 3m
