apiVersion: chaos-mesh.org/v1alpha1
kind: IOChaos
metadata:
  name: redis-disk-latency
  namespace: stage10
spec:
  action: latency
  mode: one
  selector:
    namespaces:
    - stage10
    labelSelectors:
      app: redis-cluster
  volumePath: /data
  path: '**/*'
  delay: 50ms
  percent: 50
  duration: 5m
  scheduler:
    cron: '@every 2h'
