apiVersion: chaos-mesh.org/v1alpha1
kind: IOChaos
metadata:
  name: io-throught-4
  namespace: io-throught-4
spec:
  action: latency
  mode: all
  selector:
    namespaces:
    - io-throught-4
    labelSelectors:
      app: myapp
  volumePath: /app/data
  path: /app/data/**/*
  methods:
  - read
  - write
  delay: 500ms
  percent: 10
  duration: 15m
