apiVersion: chaos-mesh.org/v1alpha1
kind: IOChaos
metadata:
  name: postgres-io-error
  namespace: fabric4l
  labels:
    app.kubernetes.io/part-of: fabric4l-chaos
    chaos-mesh.org/experiment: postgres-io-error
    chaos-mesh.org/environment: staging-only
  annotations:
    description: Inject I/O errors into PostgreSQL (STAGING ONLY)
    owner: sre-team@fabric4l.io
    severity: critical
    production_safe: 'no'
spec:
  action: fault
  mode: all
  selector:
    namespaces:
    - fabric4l
    labelSelectors:
      app: postgres
      role: primary
  volumePath: /var/lib/postgresql/data
  path: ''
  errno: 5
  percent: 5
  methods:
  - READ
  - WRITE
  duration: 2m
