apiVersion: chaos-mesh.org/v1alpha1
kind: IOChaos
metadata:
  name: redis-disk-io-delay
  namespace: chaos-testing
spec:
  action: latency
  mode: one
  selector:
    namespaces:
    - redis
    labelSelectors:
      app: redis-cluster
  duration: 4m
  scheduler:
    cron: '@every 30m'
  ioLatency:
    latency: 100ms
    correlation: '100'
    jitter: 0ms
  path: /data
  percent: 100
