apiVersion: chaos-mesh.org/v1alpha1
kind: IOChaos
metadata:
  name: io-attroverride-experiment
  namespace: chaos-mesh
spec:
  action: attrOverride
  mode: all
  selector:
    namespaces:
    - microservices
    labelSelectors:
      app: user-service
  volumePath: /data
  path: /data/users/*
  attr:
    perm: 0
    uid: 0
    gid: 0
  percent: 100
  duration: 1m
