apiVersion: chaos-mesh.org/v1alpha1
kind: IOChaos
metadata:
  name: disk-failure
  namespace: chaos-testing
spec:
  action: fault
  mode: one
  duration: 5m
  selector:
    namespaces:
    - skalean-system
    labelSelectors:
      app: postgres
  volumePath: /var/lib/postgresql/data
  path: /var/lib/postgresql/data/*
  errno: 5
  percent: 50
  scheduler:
    cron: '@every 4h'
