apiVersion: chaos-mesh.org/v1alpha1
kind: IOChaos
metadata:
  name: sp-worker-io-latency
  namespace: spatialpipe
spec:
  action: latency
  mode: one
  selector:
    namespaces:
    - spatialpipe
    labelSelectors:
      app.kubernetes.io/component: worker
  volumePath: /data
  path: /data/**
  delay: 100ms
  percent: 50
  duration: 120s
