apiVersion: chaos-mesh.org/v1alpha1
kind: IOChaos
metadata:
  name: io-throught-2
  namespace: io-throught-2
spec:
  action: mix
  mode: all
  selector:
    namespaces:
    - io-throught-2
    labelSelectors:
      app: myapp
  volumePath: /app/data
  path: /app/data/**/*
  methods:
  - read
  - write
  delay: 150ms
  errno: 5
  percent: 40
  duration: 7m
