apiVersion: chaos-mesh.org/v1alpha1
kind: IOChaos
metadata:
  name: data-plane-io-delay
  namespace: govsecure
spec:
  action: latency
  mode: one
  selector:
    namespaces:
    - govsecure
    labelSelectors:
      app: data-plane
  volumePath: /data
  path: /data/**/*
  delay: 100ms
  percent: 50
  duration: 1m
  scheduler:
    cron: '@every 12h'
