apiVersion: chaos-mesh.org/v1alpha1
kind: IOChaos
metadata:
  name: loki-storage-latency
  namespace: chaos-mesh
  labels:
    experiment-type: storage
    target-service: loki
    severity: medium
spec:
  action: latency
  mode: fixed
  value: '1'
  duration: 15m
  selector:
    namespaces:
    - observability
    labelSelectors:
      app.kubernetes.io/name: loki
      app.kubernetes.io/component: ingester
  delay: 200ms
  percent: 50
  path: /loki
  scheduler:
    cron: 0 15 * * TUE
