apiVersion: chaos-mesh.org/v1alpha1
kind: IOChaos
metadata:
  name: io-throught-3
  namespace: io-throught-3
spec:
  action: fault
  mode: all
  selector:
    namespaces:
    - io-throught-3
    labelSelectors:
      app: myapp
  volumePath: /app/data
  path: /app/data/**/*
  methods:
  - read
  - write
  errno: 5
  percent: 70
  duration: 3m
