apiVersion: chaos-mesh.org/v1alpha1
kind: IOChaos
metadata:
  name: rabbitmq-disk-io-stress
  namespace: chaos-testing
spec:
  action: fault
  mode: one
  selector:
    namespaces:
    - rabbitmq
    labelSelectors:
      app: rabbitmq-server
  duration: 4m
  scheduler:
    cron: '@every 30m'
  ioFault:
    errno: 28
    weight: 100
  path: /var/lib/rabbitmq
  percent: 100
