apiVersion: chaos-mesh.org/v1alpha1
kind: IOChaos
metadata:
  name: db-io-latency
  namespace: chaos-testing
spec:
  action: delay
  mode: all
  selector:
    namespaces:
    - llm-marketplace
    labelSelectors:
      app: postgres
  volumePath: /var/lib/postgresql/data
  path: /var/lib/postgresql/data/pg_wal/*
  delay: 500ms
  percent: 100
  duration: 3m
