apiVersion: chaos-mesh.org/v1alpha1
kind: IOChaos
metadata:
  name: io-fault-experiment
  namespace: chaos-demo
spec:
  action: fault
  mode: one
  selector:
    namespaces:
    - chaos-demo
    labelSelectors:
      app: backend
  volumePath: /app
  errno: 5
  percent: 10
  duration: 2m
