kind: StressChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: train-ticket-lab
  name: order-stress-cpu-candidate-r1
  annotations:
    chaos.origin.raw-sha256: b415e011e4b45b1dfdca07614f6bfc199097bc930ba906a6e3aab30ad938f3cc
    chaos.origin.source-yaml: raw_yaml/StressChaos/0885ce87187120d724117939.yaml
    chaos.candidate.decision: ready_candidate_with_runner
    chaos.candidate.rank: '1'
  labels:
    chaos.generated: candidate
    chaos.test-node: stress_cpu
spec:
  selector:
    namespaces:
    - train-ticket-lab
    labelSelectors:
      app: ts-order-service
  mode: one
  stressors:
    cpu:
      workers: 1
      load: 80
  duration: 45s
