kind: HTTPChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: ns-chaos-ipa-test-application
  name: abort-http-chaos
  annotations:
    experiment.chaos-mesh.org/pause: 'true'
spec:
  selector:
    namespaces:
    - ns-chaos-ipa-test-application
    labelSelectors:
      app: cinema-frontend
  mode: all
  target: Request
  abort: true
  port: 80
  path: '*'
  duration: 5m
