apiVersion: chaos-mesh.org/v1alpha1
kind: HTTPChaos
metadata:
  name: api-response-delay
  namespace: load-testing
spec:
  mode: random-max-percent
  value: '50'
  selector:
    namespaces:
    - kong
    labelSelectors:
      app: kong-proxy
  target: Response
  port: 8000
  delay: 2s
  duration: 2m
