apiVersion: chaos-mesh.org/v1alpha1
kind: HTTPChaos
metadata:
  name: http-response-body-patch
  namespace: chaos-demo
spec:
  mode: all
  selector:
    namespaces:
    - chaos-demo
    labelSelectors:
      app: backend
  target: Response
  port: 5001
  path: /data
  method: GET
  patch:
    body:
      type: JSON
      value: '{"chaos_injected":true,"injection_time":"2024-01-01T00:00:00Z"}'
  duration: 3m
