apiVersion: chaos-mesh.org/v1alpha1
kind: HTTPChaos
metadata:
  name: aiflow-http-abort
  namespace: agents-staging
spec:
  mode: one
  selector:
    namespaces:
    - agents-staging
    labelSelectors:
      app: aiflow-social-agent
  port: 8000
  path: /generate_post
  method: POST
  abort: true
  duration: 2m
