apiVersion: chaos-mesh.org/v1alpha1
kind: HTTPChaos
metadata:
  name: remote-nginx-http-abort-delay
  namespace: chaos-demo
spec:
  remoteCluster: remote-cluster-1
  mode: fixed-percent
  value: '50'
  selector:
    namespaces:
    - chaos-demo
    labelSelectors:
      app: nginx-demo
  target: Request
  port: 80
  method: GET
  path: /*
  request_headers:
    Host: nginx-demo.chaos-demo.svc.cluster.local
  delay: 1s
  abort: true
  duration: 60s
