apiVersion: chaos-mesh.org/v1alpha1
kind: HTTPChaos
metadata:
  name: superset-http-chaos
  namespace: chaos-mesh
  labels:
    experiment-type: api
    target-service: superset
    severity: medium
spec:
  mode: fixed
  value: '1'
  duration: 10m
  selector:
    namespaces:
    - data-science
    labelSelectors:
      app.kubernetes.io/name: superset
  target: Request
  port: 8088
  method: GET
  path: /api/*
  abort: true
  scheduler:
    cron: 0 18 * * FRI
