apiVersion: chaos-mesh.org/v1alpha1
kind: HTTPChaos
metadata:
  name: http-abort
  namespace: chaos-testing
spec:
  mode: random-max-percent
  value: '10'
  duration: 5m
  selector:
    namespaces:
    - skalean-system
    labelSelectors:
      app: api-gateway
  target: Request
  port: 4000
  method: POST
  path: /api/*
  abort: true
  scheduler:
    cron: '@every 4h'
