apiVersion: chaos-mesh.org/v1alpha1
kind: HTTPChaos
metadata:
  name: http-error-chaos
  namespace: staging
  labels:
    app.kubernetes.io/part-of: gp-chaos-engineering
spec:
  mode: all
  selector:
    namespaces:
    - staging
    labelSelectors:
      app.kubernetes.io/part-of: my-app
  target: Request
  port: 8080
  path: /api/*
  method: GET
  replace:
    code: 503
    body: '{"error": "chaos-mesh injected failure"}'
  duration: 60s
