apiVersion: chaos-mesh.org/v1alpha1
kind: HTTPChaos
metadata:
  name: http-abort
  namespace: llmchat
spec:
  mode: one
  selector:
    namespaces:
    - llmchat
    labelSelectors:
      app: llmchat-backend
  target: Response
  port: 3001
  path: /api/chat/completions
  abort: true
  duration: 1m
