apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: verify-grpc-delay5s
  namespace: online-boutique-lab
spec:
  action: delay
  mode: all
  selector:
    namespaces:
      - online-boutique-lab
    labelSelectors:
      app: currencyservice
  delay:
    latency: "5000ms"
    correlation: "100"
    jitter: "0ms"
  duration: 30s
  direction: to
