apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-kill
  namespace: llmchat
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
    - llmchat
    labelSelectors:
      app: llmchat-backend
  scheduler:
    cron: '@every 30m'
