apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: employee-service-pod-kill
  namespace: chaos-mesh
  labels:
    experiment: pod-kill
    service: employee-service
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
    - employee-platform
    labelSelectors:
      app: employee-service
  scheduler:
    cron: '@every 30m'
  duration: 30s
