apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-failure-multi
  namespace: default
spec:
  action: container-kill
  mode: fixed-percent
  value: '50'
  selector:
    namespaces:
    - default
    labelSelectors:
      app: cartservice
  duration: 5m
