apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: orchestrator-pod-kill
  namespace: waste-dev
  labels:
    app: chaos-testing
    experiment: pod-kill
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
    - waste-dev
    labelSelectors:
      app.kubernetes.io/instance: orchestrator
  scheduler:
    cron: '@every 2m'
