apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: service-app-pod-kill
  namespace: sre-monitoring
spec:
  action: pod-kill
  mode: one
  selector:
    labelSelectors:
      app: service-app
  scheduler:
    cron: '@every 1m'
