apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: kill-operations-pod
  namespace: chaos-mesh
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
    - bian-operations
    labelSelectors:
      app.kubernetes.io/part-of: bian-platform
  duration: 30s
