apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-kill-echo-server
  namespace: echo-server
  labels:
    app.kubernetes.io/part-of: chaos-engineering
    experiment: pod-kill
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
    - echo-server
    labelSelectors:
      app: echo-server
  duration: 30s
