apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-kill-order-service
  namespace: chaos-testing
  labels:
    experiment-type: pod-kill
    target-service: order-service
    risk-level: low
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
    - microservices-staging
    labelSelectors:
      app.kubernetes.io/name: order-service
  gracePeriod: 0
  duration: 10m
  scheduler:
    cron: '@every 2m'
