apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-kill-test
  namespace: chaos-testing
spec:
  action: pod-kill
  mode: fixed
  value: '2'
  duration: 1m
  selector:
    namespaces:
    - self-healing-prod
    labelSelectors:
      app: data-service
  scheduler:
    cron: '@every 20m'
