apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: redis-primary-failure
  namespace: helios
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
    - helios
    labelSelectors:
      app.kubernetes.io/component: redis
      role: master
  duration: 60s
  scheduler:
    cron: '@every 10m'
