apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: kafka-pod-failure
  namespace: ai-testops
spec:
  action: pod-failure
  mode: one
  duration: 45s
  selector:
    namespaces:
    - ai-testops
    labelSelectors:
      app: kafka
