apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: brain-storm-pod-failure
  namespace: default
spec:
  action: pod-failure
  mode: fixed
  value: '1'
  selector:
    namespaces:
    - default
    labelSelectors:
      app: brain-storm-backend
  duration: 2m
  scheduler:
    cron: 0 3 * * *
