apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: backend-pod-failure
  namespace: swiftguard
spec:
  action: pod-failure
  mode: one
  selector:
    namespaces:
    - swiftguard
    labelSelectors:
      app: swiftguard-backend
  duration: 90s
  scheduler:
    cron: '@weekly'
