apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: nsqd-pod-failure
  namespace: judgex
spec:
  action: pod-failure
  mode: one
  selector:
    namespaces:
    - judgex
    labelSelectors:
      app: nsqd
  duration: 3m
