apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: rolling-restart-control-api
  namespace: sentinel-system
spec:
  action: pod-kill
  mode: all
  selector:
    labelSelectors:
      app: control-api
  duration: 2m
