apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: sp-api-pod-failure
  namespace: spatialpipe
spec:
  action: pod-failure
  mode: one
  duration: 60s
  selector:
    namespaces:
    - spatialpipe
    labelSelectors:
      app.kubernetes.io/name: spatialpipe
      app.kubernetes.io/component: api
  scheduler:
    cron: '@every 30m'
