apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: postgresql-primary-failure
  namespace: databases
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
    - databases
    labelSelectors:
      app: postgresql
      role: primary
  scheduler:
    cron: '@every 12h'
  duration: 2m
