apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: aiflow-pod-kill
  namespace: agents-staging
spec:
  action: pod-kill
  mode: fixed-percent
  value: '50'
  selector:
    namespaces:
    - agents-staging
    labelSelectors:
      app: aiflow-social-agent
  duration: 1m
