apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-failure-go-api
  namespace: go-api
  labels:
    app.kubernetes.io/part-of: chaos-engineering
    experiment: pod-failure
spec:
  action: pod-failure
  mode: one
  selector:
    namespaces:
    - go-api
    labelSelectors:
      app: go-api
  duration: 60s
