apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-failure-experiment
  namespace: chaos-testing
  labels:
    app: hospital-management-system
    component: chaos
spec:
  action: pod-failure
  mode: one
  selector:
    namespaces:
    - ultimate-hms
    labelSelectors:
      app: hospital-management-system
      component: analytics
  duration: 30s
  scheduler:
    cron: '@every 24h'
