apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: kill-control-api-pod
  namespace: sentinel-system
spec:
  action: pod-kill
  mode: one
  selector:
    labelSelectors:
      app: control-api
  scheduler:
    cron: '@every 10m'
  duration: 30s
