apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: openstack-pod-kill
  namespace: chaos-engineering
  labels:
    experiment: pod-kill
    service: openstack-services
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
    - openstack-blue
    - openstack-green
    labelSelectors:
      component: api-server
  duration: 10m
  scheduler:
    cron: 0 3 * * 2
