apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-failure-anomaly-detector
  namespace: chaos-testing
  labels:
    experiment: pod-failure
    tier: advanced
    app.kubernetes.io/part-of: self-healing-infra
  annotations:
    chaos.selfhealing.io/description: Simulate pod failure on anomaly-detector
    chaos.selfhealing.io/expected-recovery-seconds: '90'
spec:
  action: pod-failure
  mode: one
  selector:
    namespaces:
    - self-healing
    labelSelectors:
      app.kubernetes.io/name: anomaly-detector
  duration: 60s
