apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: mimir-pod-failure
  namespace: chaos-mesh
  labels:
    experiment-type: availability
    target-service: mimir
    severity: medium
spec:
  action: pod-kill
  mode: fixed-percent
  value: '25'
  duration: 5m
  selector:
    namespaces:
    - observability
    labelSelectors:
      app.kubernetes.io/name: mimir
      app.kubernetes.io/component: ingester
  scheduler:
    cron: '@daily'
