apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-failure
  namespace: cathedral
spec:
  action: pod-failure
  mode: one
  selector:
    namespaces:
    - cathedral
    labelSelectors:
      app: cathedral-api
  duration: 30s
  scheduler:
    cron: '@every 10m'
