apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: payment-service-kill
  namespace: final-project
spec:
  action: pod-kill
  mode: one
  selector:
    labelSelectors:
      app.kubernetes.io/instance: order-service
  duration: 1m
  scheduler:
    cron: '@every 2m'
