apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: vernemq-pod-failure
  namespace: chaos-mesh
  labels:
    experiment-type: availability
    target-service: vernemq
    severity: medium
    storage.samcloud.online/tier: standard
spec:
  action: pod-kill
  mode: fixed-percent
  value: '33'
  duration: 10m
  selector:
    namespaces:
    - storage
    labelSelectors:
      app.kubernetes.io/name: vernemq
  scheduler:
    cron: 0 14 * * MON
