apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: service-a-random-kill
  namespace: canary-playground
spec:
  action: pod-kill
  mode: one
  duration: 30s
  scheduler:
    cron: '*/5 * * * *'
  selector:
    labelSelectors:
      app: service-a
