apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: nsqd-pod-kill
  namespace: judgex
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
    - judgex
    labelSelectors:
      app: nsqd
  duration: 1m
  gracePeriod: 3
