apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: api-kill
  namespace: rocketvault
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
    - rocketvault
    labelSelectors:
      app: api
  duration: 1m
