apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: kill-pipeline-controller-pod
  namespace: sentinel-system
spec:
  action: pod-kill
  mode: one
  selector:
    labelSelectors:
      app: pipeline-controller
  scheduler:
    cron: '@every 15m'
  duration: 30s
