apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-failure-testcase
  namespace: chaos
spec:
  action: pod-failure
  mode: one
  duration: 3m
  selector:
    namespaces:
    - default
    labelSelectors:
      app: nginx
