apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-kill-experiment
  namespace: qbitel
spec:
  action: pod-kill
  mode: fixed
  value: '1'
  duration: 60s
  selector:
    namespaces:
    - qbitel
    labelSelectors:
      app: qbitel
      component: api
  scheduler:
    cron: '@every 2h'
