kind: PodChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: store
  name: adservice-pod-failure
  annotations:
    experiment.chaos-mesh.org/pause: 'true'
spec:
  selector:
    namespaces:
    - store
    labelSelectors:
      app: adservice
  mode: all
  action: pod-failure
