apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pesitwizard-leader-failure
  namespace: staging
  labels:
    app: pesitwizard
    chaos-type: pod-kill
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
    - staging
    labelSelectors:
      app: pesitwizard-server
      role: leader
  scheduler:
    cron: '@every 1h'
