apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-crash-amf
  namespace: open5gs
spec:
  action: pod-kill
  mode: all
  selector:
    namespaces:
    - open5gs
    labelSelectors:
      app.kubernetes.io/name: amf
      app.kubernetes.io/instance: open5gs
  duration: 1m
