apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: remitflow-server-pod-kill
  namespace: remitflow-staging
  labels:
    app.kubernetes.io/part-of: remitflow
    chaos-type: pod
    target: server
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
    - remitflow-staging
    labelSelectors:
      app: remitflow-server
  gracePeriod: 0
  duration: 1m
  scheduler:
    cron: '@every 6h'
