apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: e6-dns
  namespace: chaos-mesh
spec:
  schedule: 40 6 * * *
  concurrencyPolicy: Forbid
  historyLimit: 5
  type: Workflow
  workflow:
    entry: e6
    templates:
    - name: e6
      templateType: Serial
      deadline: 10m
      children:
      - preflight-health
      - impair-and-watch
    - name: preflight-health
      templateType: StatusCheck
      deadline: 2m
      statusCheck:
        mode: Synchronous
        type: HTTP
        http:
          url: https://dev.seqtoid.org/health_check
          method: GET
          criteria:
            statusCode: '200'
    - name: impair-and-watch
      templateType: Parallel
      deadline: 5m
      children:
      - dns-fail-dependency
      - steady-state-during
    - name: dns-fail-dependency
      templateType: DNSChaos
      deadline: 2m
      dnsChaos:
        action: error
        mode: one
        selector:
          namespaces:
          - seqtoid-dev
          labelSelectors:
            app.kubernetes.io/component: web
        patterns:
        - vpc-czid-dev-heatmap-es-5ixjn2y6cndlbnwlymxnqo5jpq.us-west-2.es.amazonaws.com
    - name: steady-state-during
      templateType: StatusCheck
      deadline: 4m
      statusCheck:
        mode: Continuous
        type: HTTP
        duration: 3m
        intervalSeconds: 2
        failureThreshold: 5
        recordsHistoryLimit: 100
        http:
          url: https://dev.seqtoid.org/health_check
          method: GET
          criteria:
            statusCode: '200'
