apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: chaos-24h-network-loss
  namespace: backend
spec:
  schedule: 30 */6 * * *
  type: NetworkChaos
  concurrencyPolicy: Forbid
  historyLimit: 3
  networkChaos:
    action: loss
    mode: fixed-percent
    value: '60'
    selector:
      namespaces:
      - backend
      labelSelectors:
        chaos-target: 'true'
    loss:
      loss: '10'
      correlation: '25'
    duration: 20m
