apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: chaos-24h-network-delay
  namespace: backend
spec:
  schedule: 0 */6 * * *
  type: NetworkChaos
  concurrencyPolicy: Forbid
  historyLimit: 3
  networkChaos:
    action: delay
    mode: all
    selector:
      namespaces:
      - backend
      labelSelectors:
        chaos-target: 'true'
    delay:
      latency: 150ms
      correlation: '35'
      jitter: 50ms
    duration: 20m
