apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: entmoot-site-partition-60s
  namespace: entmoot
spec:
  schedule: 0 */2 * * *
  historyLimit: 5
  concurrencyPolicy: Forbid
  type: NetworkChaos
  networkChaos:
    action: partition
    mode: all
    selector:
      namespaces:
      - entmoot
      labelSelectors:
        app: entmoot
      pods:
        entmoot:
        - entmoot-0
    direction: both
    target:
      mode: all
      selector:
        namespaces:
        - entmoot
        labelSelectors:
          app: entmoot
        pods:
          entmoot:
          - entmoot-1
          - entmoot-2
    duration: 60s
