apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: weekly-resilience-test
  namespace: chaos-testing
spec:
  schedule: 0 1 * * 0
  type: Workflow
  workflowSpec:
    entry: entry
    templates:
    - name: entry
      templateType: Serial
      children:
      - pod-chaos
      - network-chaos
    - name: pod-chaos
      templateType: PodChaos
      podChaos:
        action: pod-kill
        mode: one
        selector:
          namespaces:
          - elevatediq
          labelSelectors:
            tier: frontend
        duration: 1m
    - name: network-chaos
      templateType: NetworkChaos
      networkChaos:
        action: delay
        mode: all
        selector:
          namespaces:
          - elevatediq
          labelSelectors:
            tier: backend
        delay:
          latency: 150ms
        duration: 2m
