apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: chaos-24h-bandwidth-limit
  namespace: backend
spec:
  schedule: 0 2-23/6 * * *
  type: NetworkChaos
  concurrencyPolicy: Forbid
  historyLimit: 3
  networkChaos:
    action: bandwidth
    mode: all
    selector:
      namespaces:
      - backend
      labelSelectors:
        chaos-target: 'true'
    bandwidth:
      rate: 3mbps
      limit: 20971520
      buffer: 10000
    duration: 20m
