apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: chaos-24h-dns-fault
  namespace: backend
spec:
  schedule: 0 3-23/6 * * *
  type: DNSChaos
  concurrencyPolicy: Forbid
  historyLimit: 3
  dnsChaos:
    action: error
    mode: all
    selector:
      namespaces:
      - backend
      labelSelectors:
        chaos-target: 'true'
    patterns:
    - kubernetes.default.svc.cluster.local
    - myapp.backend.svc.cluster.local
    duration: 15m
