apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: gateway-pod-kill
  namespace: baalvion-edge
spec:
  schedule: '*/10 * * * *'
  type: PodChaos
  podChaos:
    action: pod-kill
    mode: one
    selector:
      namespaces:
      - baalvion-edge
      labelSelectors:
        app: gateway
