apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: pod-{deploy_id}
  namespace:
    namespace: null
spec:
  schedule: '*/{timer} * * * *'
  historyLimit: 5
  concurrencyPolicy: Forbid
  type: PodChaos
  podChaos:
    action: pod-failure
    mode: all
    selector:
      namespaces:
      - namespace: null
    duration: 10s
