apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: daily-chaos-experiments
  namespace: chaos-testing
spec:
  concurrencyPolicy: Forbid
  schedule: 0 2 * * 6
  startingDeadlineSeconds: 3600
  workflows:
  - name: infra-pod-failure-test
