apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: scheduled-io-chaos
  namespace: chaos-testing
spec:
  schedule: '@every 3h'
  type: IOChaos
  historyLimit: 5
  ioChaos:
    action: delay
    mode: one
    selector:
      namespaces:
      - llm-marketplace
      labelSelectors:
        tier: backend
    volumePath: /app
    path: /app/**/*
    delay: 150ms
    percent: 50
    duration: 4m
