apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: pod-failure-node04
  namespace: chaos-mesh
  labels:
    app.kubernetes.io/name: chaos-mesh
    app.kubernetes.io/component: experiment
    chaos-mesh.org/experiment-type: pod-failure
spec:
  schedule: 0 12 1 * *
  type: PodChaos
  historyLimit: 3
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 60
  podChaos:
    action: pod-failure
    mode: all
    selector:
      nodeSelectors:
        kubernetes.io/hostname: node04
      namespaces:
      - falco
      - loki
      - lifeonabike
      - unipoller
      - argo-workflows
      - argo-events
    duration: 5m
