apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: graduated-stress
  namespace: chaos-testing
spec:
  schedule: '@every 2h'
  type: StressChaos
  historyLimit: 3
  stressChaos:
    mode: one
    selector:
      namespaces:
      - llm-marketplace
      labelSelectors:
        tier: backend
    stressors:
      cpu:
        workers: 1
        load: 50
    duration: 5m
