apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library
  namespace: chaosatlas-immich
  labels:
    app.kubernetes.io/part-of: chaosatlas-apps
    chaosatlas.io/application: immich
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard
