apiVersion: chaos-mesh.org/v1alpha1
kind: Workflow
metadata:
  name: multi-validator-latency-__LATENCY__
  namespace: chaos-mesh
  labels:
    purpose: multi-validator-latency-test
spec:
  entry: serial-reset-and-wait
  templates:
  - name: serial-reset-and-wait
    templateType: Serial
    children:
    - kill-validators
    - wait-pod-recovery
    - experiment-window
  - name: kill-validators
    templateType: PodChaos
    deadline: 60s
    podChaos:
      action: pod-kill
      mode: all
      selector:
        namespaces:
        - default
        labelSelectors:
          app.kubernetes.io/component: maru
          app.kubernetes.io/component-role: validator
  - name: wait-pod-recovery
    templateType: Suspend
    deadline: 45s
  - name: experiment-window
    templateType: Suspend
    deadline: __EXPERIMENT_DURATION__
