apiVersion: chaos-mesh.org/v1alpha1
kind: Workflow
metadata:
  namespace: default
  name: stress-on-recovery
spec:
  entry: stress-on-fail-and-recovery
  templates:
  - name: stress-on-fail-and-recovery
    templateType: Parallel
    deadline: 4m
    children:
    - fail-1m
    - stress-2m
  - name: fail-1m
    templateType: PodChaos
    deadline: 1m
    podChaos:
      selector:
        namespaces:
        - default
      mode: all
      action: pod-failure
  - name: stress-2m
    templateType: StressChaos
    deadline: 2m
    stressChaos:
      selector:
        namespaces:
        - default
      mode: all
      stressors:
        cpu:
          workers: 100
          load: 99
