apiVersion: chaos-mesh.org/v1alpha1
kind: Workflow
metadata:
  name: concert-chaos
  namespace: chaos-mesh
spec:
  entry: concert-sequence
  templates:
  - name: concert-sequence
    templateType: Serial
    deadline: 20m
    children:
    - wait-until-peak
    - kill-driver
    - wait-1min
    - redis-delay
    - wait-1min
    - mongo-loss
    - wait-1min
    - kill-gateway
  - name: wait-until-peak
    templateType: Suspend
    deadline: 8m
  - name: wait-1min
    templateType: Suspend
    deadline: 1m
  - name: kill-driver
    templateType: PodChaos
    deadline: 60s
    podChaos:
      action: pod-kill
      mode: one
      selector:
        namespaces:
        - default
        labelSelectors:
          app: driver-service
  - name: redis-delay
    templateType: NetworkChaos
    deadline: 60s
    networkChaos:
      action: delay
      mode: one
      selector:
        namespaces:
        - default
        labelSelectors:
          app: redis
      delay:
        latency: 50ms
        correlation: '25'
        jitter: 10ms
  - name: mongo-loss
    templateType: NetworkChaos
    deadline: 60s
    networkChaos:
      action: loss
      mode: one
      selector:
        namespaces:
        - default
        labelSelectors:
          app: mongodb
      loss:
        loss: '10'
        correlation: '25'
  - name: kill-gateway
    templateType: PodChaos
    deadline: 60s
    podChaos:
      action: pod-kill
      mode: one
      selector:
        namespaces:
        - default
        labelSelectors:
          app: api-gateway
