apiVersion: chaos-mesh.org/v1alpha1
kind: Workflow
metadata:
  name: mimir-chaos-testing
  namespace: mimir-production
spec:
  entry: sequential-chaos
  templates:
  - name: sequential-chaos
    templateType: Serial
    deadline: 20m
    children:
    - pod-chaos-test
    - network-chaos-test
    - stress-chaos-test
  - name: pod-chaos-test
    templateType: PodChaos
    deadline: 5m
    podChaos:
      action: pod-kill
      mode: one
      selector:
        namespaces:
        - mimir-production
        labelSelectors:
          app: mimir-web
  - name: network-chaos-test
    templateType: NetworkChaos
    deadline: 5m
    networkChaos:
      action: partition
      mode: one
      selector:
        namespaces:
        - mimir-production
        labelSelectors:
          app: mimir-api
      direction: to
      target:
        mode: one
        selector:
          namespaces:
          - mimir-production
          labelSelectors:
            app: postgres
  - name: stress-chaos-test
    templateType: StressChaos
    deadline: 10m
    stressChaos:
      mode: one
      selector:
        namespaces:
        - mimir-production
        labelSelectors:
          app: mimir-worker
      stressors:
        memory:
          workers: 1
          size: 512MB
