apiVersion: chaos-mesh.org/v1alpha1
kind: KernelChaos
metadata:
  name: data-plane-disk-failure
  namespace: govsecure
spec:
  mode: one
  selector:
    namespaces:
    - govsecure
    labelSelectors:
      app: data-plane
  failKernRequest:
    callchain:
    - funcname: write
    failtype: 0
  duration: 10s
  scheduler:
    cron: '@every 24h'
