apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: ob-productcatalog-kill-r1
  namespace: online-boutique-lab
spec:
  action: pod-kill
  mode: all
  selector:
    namespaces:
      - online-boutique-lab
    labelSelectors:
      app: productcatalogservice
  duration: "60s"
