#!/usr/bin/env python3
"""Build and freeze LLM knowledge-ablation Gate 0-2 artifacts (protocol v1, sections 4-6, 12).
Remediation v2 (2026-08-10, human review findings):

  Fix 1  - LLM-generic is now generic-rules-only: the knowledge supplement is the
           curated `knowledge_ablation_generic_rules_v1.json` (SE/DP/JE distilled to
           project-free rule statements; historical project names, service names,
           candidate IDs, experiment/corpus evidence, file paths and project results
           removed). The raw snapshot SE/DP/JE are never sent to any arm.
  Fix 2  - knowledge_snapshot_manifest full_pre/status are read from the LIVE snapshot
           (SOCIALNET: full_pre=True), not hardcoded.
  Fix 3  - all arm views, prompt bundles, leakage audits and manifests are regenerated.
  Fix 4  - leakage audit scans HISTORICAL project terms (prior projects
           train-ticket/online-boutique/otel-demo/sock-shop + candidate-ID prefixes +
           service names) across ALL arms, plus current held-out project terms in the
           generic knowledge sections, plus project-specific evidence markers.
  Fix 5  - ESHOP's third arm is renamed `LLM-partial-pre` (full_pre not claimable);
           SOCIALNET keeps `LLM-full-pre`.
  Fix 6  - pools are regenerated byte-identically (hashes unchanged); the manifest
           declares that 40/30 formal pools are NOT protocol-conformant formal-48
           pools and require a protocol amendment before formal execution.
  Fix 7  - a separate candidate_id -> mutation_path mapping plus per-candidate
           NetworkChaos/PodChaos YAML are generated under knowledge_ablation_mutations/;
           the frozen candidate pools keep `mutation_path: null` (never modified).

It never deploys, never injects, never runs experiments, and refuses to overwrite
existing artifacts (fail-closed). All outputs are written under
artifacts/experiments/knowledge_ablation_*.
"""

from __future__ import annotations

import hashlib
import json
import random
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from decision_engine import validate_knowledge_snapshot  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
EXPERIMENTS = ROOT / "artifacts" / "experiments"
HELDOUT = EXPERIMENTS / "heldout"

# Pinned SHA-256 of the generic knowledge libraries (must match the values
# embedded in the frozen snapshots; the builder refuses to proceed otherwise).
PINNED_KNOWLEDGE_SHA = {
    "selection_experience.json": "f7280be785e34504fdcde76f81db027c32d5db6d572a2fc648c65eb347704fc1",
    "defense_pattern_library.json": "afffb6ada45c947a3110dec6365152af8260358a45f7eb6e415926de70f557d8",
    "judgment_experience.json": "7756d8d3beb0ea6a4644a3d2ecff117b09eabe62ad3e1d2a33aee61c2c6eead6",
}

# Curated generic-rules-only knowledge supplement (Fix 1). Its SHA-256 is pinned;
# the builder refuses to proceed if the file drifts.
GENERIC_RULES_FILE = "artifacts/experiments/knowledge_ablation_generic_rules_v1.json"
GENERIC_RULES_SHA = "5b813997e5742dc9c59938171ff53cdf1ab37a18c7f01c3530058416b745f258"

# Pre-registered LLM selection seeds: identical across arms (paired design), a
# separate phase-offset block so pilot and formal permutations never collide.
PILOT_SEEDS = [1001, 1002, 1003]
FORMAL_SEEDS = [2001, 2002, 2003]
SEEDS = {"pilot": PILOT_SEEDS, "formal": FORMAL_SEEDS}
BUDGET_K = {"pilot": 8, "formal": 10}

# Pool quotas (protocol v1.1 section 8 / ablation protocol v1 section 5).
POOL_SIZE = {"pilot": 24, "formal": 48}
PROTECTION_QUOTA = {"pilot": (8, 8, 8), "formal": (16, 16, 16)}  # protected/unprotected/unknown

# Model/endpoint configuration pre-registered for all arms (same across arms).
LLM_CONFIG = {
    "model_identifier": "deepseek-v4-flash",
    "endpoint": "https://api.deepseek.com/v1",
    "endpoint_note": "OpenAI-compatible POST /chat/completions; identical across all arms",
    "temperature": 0.2,
    "max_output_tokens": 2048,
    "timeout_seconds": 180,
    "json_mode": True,
    "retry_policy": "transport failures only; same seed and exact same prompt; "
                    "parser-invalid outputs are LLM decision failures and are not retried",
}

# --------------------------------------------------------------------------
# Pre-registered neutral rules
# --------------------------------------------------------------------------

# CLS rules: static protection classification (out-of-band; never an LLM input).
CLASSIFICATION_RULES = [
    {"rule_id": "CLS-001", "rule": "edge has statically-confirmed explicit_timeout AND loss_bounded=true -> protected for delay AND loss"},
    {"rule_id": "CLS-002", "rule": "edge has statically-confirmed explicit_timeout with loss_bounded=false -> protected for delay (bounded to the timeout); unprotected for loss (loss not statically bounded)"},
    {"rule_id": "CLS-003", "rule": "edge has statically-confirmed absence of a bounded-timeout/deadline defense (no_timeout or no per-call deadline) -> unprotected for delay and loss"},
    {"rule_id": "CLS-004", "rule": "kill candidate -> protected only if a static availability oracle confirms a defense (replicas>=2 or PDB or HPA); unprotected only if single-replica without PDB is confirmed; otherwise unknown"},
    {"rule_id": "CLS-005", "rule": "no static evidence sufficient to classify the family-specific defense -> unknown"},
]

# Pool construction rule (protocol v1.1 section 8 / ablation v1 section 5).
POOL_CONSTRUCTION_RULE = (
    "1) candidate universe = statically-documented service call edges from the frozen intake "
    "(business edges first, then event-bus/infra edges, matching the intake dependency graph order), "
    "each edge yielding one candidate per supported network family, plus one kill candidate per "
    "documented business service where the kill family is supported; "
    "2) kill family marked unavailable when no deployment manifest exists at the frozen commit "
    "(never borrowed from another project); "
    "3) per-family quota filled by fixed rotation: pilot 8 per supported family / formal 16 per "
    "supported family; when fewer families are supported the same rotation fills the total pool size; "
    "4) shortfalls (family targets the project cannot satisfy) are recorded as deviations, never "
    "silently rebalanced after seeing results."
)

# Mutation YAML pre-registered parameter tiers (Fix 7): fixed neutral tiers,
# mirroring the repository's frozen mutation format.
MUTATION_PARAMS = {
    "delay": {"action": "delay", "latency": "2000ms", "jitter": "0ms", "correlation": "100", "duration": "30s", "direction": "to"},
    "loss": {"action": "loss", "loss": "100", "correlation": "100", "duration": "30s", "direction": "to"},
    "kill": {"action": "pod-kill", "duration": "30s"},
}

# --------------------------------------------------------------------------
# Project static data (authoritative sources: intake reports + snapshots, frozen 2026-08-10)
# --------------------------------------------------------------------------

ESHOP_EDGES = [
    # (edge_key, source, target, contract_key_or_None)
    ("webapp->basket-api", "webapp", "Basket.API", None),
    ("webapp->catalog-api", "webapp", "Catalog.API", "ESHOP-webapp->catalog"),
    ("webapp->ordering-api", "webapp", "Ordering.API", "ESHOP-webapp->ordering"),
    ("webapp->identity-api", "webapp", "Identity.API", None),
    ("mobile-bff->catalog-api", "mobile-bff", "Catalog.API", None),
    ("mobile-bff->ordering-api", "mobile-bff", "Ordering.API", None),
    ("mobile-bff->identity-api", "mobile-bff", "Identity.API", None),
    ("webhookclient->webhooks-api", "webhookclient", "Webhooks.API", None),
    ("webapp->rabbitmq", "webapp", "RabbitMQ", None),
    ("basket-api->redis", "Basket.API", "Redis", None),
    ("basket-api->rabbitmq", "Basket.API", "RabbitMQ", None),
    ("catalog-api->rabbitmq", "Catalog.API", "RabbitMQ", None),
    ("catalog-api->catalog-db", "Catalog.API", "catalog-db", None),
    ("ordering-api->rabbitmq", "Ordering.API", "RabbitMQ", None),
    ("ordering-api->order-db", "Ordering.API", "order-db", None),
    ("orderprocessor->rabbitmq", "OrderProcessor", "RabbitMQ", None),
    ("orderprocessor->order-db", "OrderProcessor", "order-db", None),
    ("paymentprocessor->rabbitmq", "PaymentProcessor", "RabbitMQ", None),
    ("webhooks-api->rabbitmq", "Webhooks.API", "RabbitMQ", None),
    ("webhooks-api->webhooks-db", "Webhooks.API", "webhooks-db", None),
]

SOCIALNET_EDGES = [
    # Only the source-verified contract edges (settled Stage C2 snapshot): the
    # 7 ComposePost edges + 2 HomeTimeline edges. nginx-thrift is documented as
    # a router ("HTTP routes to services") without enumerated per-edge contract
    # evidence, so no nginx-thrift edge candidate is generated (intake: "only
    # source-verified edges may enter the frozen pool").
    ("compose-post->post-storage", "compose-post", "post-storage", "SOCIALNET-composepost->poststorage"),
    ("compose-post->user-timeline", "compose-post", "user-timeline", "SOCIALNET-composepost->usertimeline"),
    ("compose-post->text", "compose-post", "text", "SOCIALNET-composepost->text"),
    ("compose-post->user", "compose-post", "user", "SOCIALNET-composepost->user"),
    ("compose-post->media", "compose-post", "media", "SOCIALNET-composepost->media"),
    ("compose-post->home-timeline", "compose-post", "home-timeline", "SOCIALNET-composepost->hometimeline"),
    ("compose-post->unique-id", "compose-post", "unique-id", "SOCIALNET-composepost->uniqueid"),
    ("home-timeline->post-storage", "home-timeline", "post-storage", "SOCIALNET-hometimeline->poststorage"),
    ("home-timeline->social-graph", "home-timeline", "social-graph", "SOCIALNET-hometimeline->socialgraph"),
]

# Kill targets = the 12 helm-verified services from the settled snapshot
# availability_kubernetes (media-frontend is NOT in the helm audit and is
# therefore excluded as a kill target).
SOCIALNET_KILL_TARGETS = [
    "compose-post-service", "post-storage-service", "user-timeline-service",
    "text-service", "user-service", "media-service", "home-timeline-service",
    "social-graph-service", "unique-id-service", "user-mention-service",
    "url-shorten-service", "nginx-thrift",
]

PROJECTS = {
    "ESHOP": {
        "canonical_url": "https://github.com/dotnet/eShop",
        "commit": "9b4f9434f46fdc5c1a6e9e936af2868340cdbc48",
        "ref": "main (shallow, 2026-08-10)",
        "license": "MIT",
        "source_path": "/root/heldout_src/eshop (outside repo, not committed)",
        "snapshot_file": "eshop_knowledge_snapshot_pre.json",
        "intake_file": "eshop_intake_report.json",
        "snapshot_status": "blocked",
        "snapshot_full_pre": False,
        "edges": ESHOP_EDGES,
        "kill_targets": [],
        "supported_families": ["delay", "loss"],
        "kill": {
            "available": False,
            "reason": "no docker-compose/k8s manifest exists at the frozen commit 9b4f9434; "
                      "kill (PodChaos) has no deployment target (intake fault_families.kill = "
                      "blocked_pending_deployment_target)",
        },
        "availability_scope": {"compose": "unavailable", "kubernetes": "unavailable", "deployment_target": "unknown"},
        "observability_neutral": "OpenTelemetry (logs/metrics/traces, OTLP)",
        "workload_neutral": "documented call graph from the frozen intake (development orchestration)",
        # Fix 5: ESHOP snapshot is blocked (availability unavailable) -> the
        # project-specific pre arm is `LLM-partial-pre`, full_pre NOT claimable.
        "third_arm": {
            "id": "LLM-partial-pre",
            "dir": "partial-pre",
            "view_key": "partial_pre",
            "full_pre_claimable": False,
            "reason": "ESHOP snapshot status=blocked, full_pre=False (no k8s/compose manifest at "
                      "the frozen commit; availability unavailable) -> a full-pre arm cannot be "
                      "claimed; only partial static-contract knowledge is available.",
        },
    },
    "SOCIALNET": {
        "canonical_url": "https://github.com/delimitrou/DeathStarBench (socialNetwork/)",
        "commit": "6ecb09706140f8730b5385c08f1386c654c3c526",
        "ref": "master (shallow sparse socialNetwork/, 2026-08-10)",
        "license": "GPL-2.0",
        "source_path": "/root/heldout_src/socialnet/socialNetwork (outside repo, not committed)",
        "snapshot_file": "socialnet_knowledge_snapshot_pre.json",
        "intake_file": "socialnet_intake_report.json",
        "snapshot_status": "valid",
        "snapshot_full_pre": True,
        "edges": SOCIALNET_EDGES,
        "kill_targets": SOCIALNET_KILL_TARGETS,
        "supported_families": ["delay", "loss", "kill"],
        "kill": {
            "available": True,
            "reason": "helm-chart 28 sub-charts per-file audited (Stage C2): replicas=1, "
                      "no business probes, no PDB, HPA disabled -> kill targets verified and "
                      "classifiable (CLS-004)",
        },
        "availability_scope": {"compose": "verified", "kubernetes": "verified", "deployment_target": "helm_chart"},
        "observability_neutral": "Jaeger distributed tracing (OpenTracing)",
        "workload_neutral": "documented call graph from the frozen intake (thrift services behind nginx-thrift entry)",
        "third_arm": {
            "id": "LLM-full-pre",
            "dir": "full-pre",
            "view_key": "full_pre",
            "full_pre_claimable": True,
            "reason": "SOCIALNET snapshot status=valid, full_pre=True (helm availability verified, "
                      "provenance complete) -> full-pre arm is claimable.",
        },
    },
}

# Forbidden-term sets for the leakage audit. PROJECT_TERMS are the exact
# current held-out project-specific markers; they must be absent from generic
# knowledge sections but are allowed in the project_specific section and in the
# neutral intake summary (which describes the project under test).
PROJECT_TERMS = {
    "ESHOP": ["ESHOP", "eShop", "eshop", "dotnet/eShop", "9b4f9434",
              "Basket.API", "Catalog.API", "Ordering.API", "Identity.API",
              "Webhooks.API", "PaymentProcessor", "OrderProcessor", "WebApp",
              "WebhookClient", "catalog-api", "ordering-api", "mobile-bff"],
    "SOCIALNET": ["SOCIALNET", "socialnet", "socialNetwork", "DeathStarBench",
                  "Hotel", "hotel", "mediaMicroservices", "6ecb0970",
                  "ComposePost", "compose-post", "HomeTimeline", "home-timeline",
                  "PostStorage", "post-storage", "SocialGraph", "social-graph",
                  "UserTimeline", "user-timeline", "UserMention", "user-mention",
                  "UrlShorten", "url-shorten", "UniqueId", "unique-id",
                  "nginx-thrift", "media-frontend"],
}

# Fix 4: HISTORICAL project terms - prior (non-held-out) projects and their
# candidate-ID prefixes and service names. These must be absent from EVERY arm's
# knowledge, intake, descriptors and rendered prompts.
HISTORICAL_TERMS = [
    # project names
    "train-ticket", "train ticket", "trainticket", "TrainTicket", "TT-",
    "online-boutique", "online boutique", "onlineboutique", "OnlineBoutique", "OB-",
    "otel-demo", "otel demo", "oteldemo", "OTel", "OTEL-",
    "sock-shop", "sock shop", "sockshop", "Sock Shop", "SOCK-",
    "knowledge_base", "KB-", "K7-", "chaos_eater", "fastfi",
    # prior-project service names / evidence markers (generic knowledge must be free of these)
    "paymentservice", "checkoutservice", "productcatalogservice", "cartservice",
    "shippingservice", "currencyservice", "adservice", "emailservice",
    "chargeCard", "main.go", "application.yml", "OrdersController.java",
    "catalogue-db", "carts-db", "orders-db", "ts-station", "ts-order", "ts-basic",
    "station-service", "order-service", "basic-service", "front-end",
]

# Terms that encode contract/defense facts (blind and generic arms must not see them).
CONTRACT_TERMS = ["no_timeout", "explicit_timeout", "loss_bounded", "timeout_ms",
                  "per-call deadline", "per-request timeout", "AddPolicyHandler",
                  "CircuitBreaker", "Timeout", "Retry", "deadline"]
# Terms that encode deployment/availability facts (blind and generic arms must not see them).
AVAILABILITY_TERMS = ["docker-compose", "k8s", "kubernetes", "helm", "replicas",
                      "PDB", "HPA", "deployment_target", "availability_scope", "manifest"]
# Narrow markers that can never legitimately appear in any LLM input. Broad
# verdict words (weakness/severity/confirmed/...) DO appear in the generic
# rules as concepts, so per-candidate verdict detection is done structurally.
NARROW_MARKERS = ["oracle_label", "stored-out-of-band", "candidate_protection_classification",
                  "environment_blocked", "final_verdict", "quota_compliance",
                  "classifications", "root_cause", "posthoc", "post_hoc"]
# Project-specific evidence markers (Fix 4): fields/terms that only belong to
# experiment evidence and must never appear in generic-rules-only knowledge.
EVIDENCE_MARKERS = ["experiment_evidence", "corpus_evidence", "evidence_cases",
                    "evidence_files", "evidence_count", "mutation_path", "oracle_label"]
# Knowledge-library markers (blind arm must not see any knowledge section).
KNOWLEDGE_MARKERS = ["selection_experience", "defense_pattern_library", "judgment_experience",
                     "SE-CORE-CHAIN", "SE-LOSS-STRONGEST", "SE-NETWORK-FAMILY",
                     "SE-CROSSPROJECT", "SE-SIDEEFFECT", "SE-TEST-HYGIENE",
                     "DP-DEFENSE", "DP-BOUNDED", "JE-CONTRACT", "JE-COUPLING",
                     "JE-OBSERVABILITY", "JE-RECOVERY", "JE-RISK"]
# Forbidden JSON fields that no LLM bundle may contain (checked structurally).
FORBIDDEN_FIELDS = ["oracle_label", "static_evidence_refs", "candidate_protection_classification",
                    "classification", "verdict", "quota_compliance", "evidence_cases",
                    "evidence_files", "evidence_count", "corpus_evidence", "experiment_evidence"]


# --------------------------------------------------------------------------
# Helpers
# --------------------------------------------------------------------------

def sha256_bytes(b: bytes) -> str:
    return hashlib.sha256(b).hexdigest()


def sha256_file(rel: str) -> str:
    path = ROOT / rel
    if not path.exists():
        raise FileNotFoundError(rel)
    return sha256_bytes(path.read_bytes())


def load_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, obj: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(obj, indent=2, sort_keys=True, ensure_ascii=False) + "\n", encoding="utf-8")


def norm_token(s: str) -> str:
    """Normalize a service name into a candidate-ID-safe token."""
    return s.lower().replace(".", "-").replace("->", "-").replace(" ", "")


def candidate_id_for_edge(project: str, edge_key: str, family: str) -> str:
    return f"{project}-{norm_token(edge_key)}-{family}"


def candidate_id_for_kill(project: str, service: str) -> str:
    return f"{project}-kill-{norm_token(service)}"


def seeded_permutation(n: int, seed: int) -> list[int]:
    """Fisher-Yates over registration-order indices [0..n-1], seeded."""
    rng = random.Random(seed)
    idx = list(range(n))
    for i in range(n - 1, 0, -1):
        j = rng.randint(0, i)
        idx[i], idx[j] = idx[j], idx[i]
    return idx


def json_text(obj: Any) -> str:
    return json.dumps(obj, indent=2, sort_keys=True, ensure_ascii=False)


def scan_terms(text: str, terms: list[str]) -> dict[str, int]:
    """Case-insensitive word-boundary term scan. Uses regex word boundaries so
    a term like 'otel' does not match the substring inside 'hotel'."""
    import re
    lower = text.lower()
    hits: dict[str, int] = {}
    for t in terms:
        pat = r"\b" + re.escape(t.lower()) + r"\b"
        c = len(re.findall(pat, lower))
        if c:
            hits[t] = c
    return hits


def find_forbidden_fields(obj: Any, forbidden: list[str], path: str = "$") -> list[str]:
    found: list[str] = []
    if isinstance(obj, dict):
        for k, v in obj.items():
            if k in forbidden:
                found.append(f"{path}.{k}")
            found += find_forbidden_fields(v, forbidden, f"{path}.{k}")
    elif isinstance(obj, list):
        for i, v in enumerate(obj):
            found += find_forbidden_fields(v, forbidden, f"{path}[{i}]")
    return found


# --------------------------------------------------------------------------
# Gate 0: verification
# --------------------------------------------------------------------------

def verify_gate0(protocol_sha: str) -> None:
    for rel, expected in PINNED_KNOWLEDGE_SHA.items():
        actual = sha256_file(f"artifacts/experiments/{rel}")
        if actual != expected:
            raise RuntimeError(f"FAIL-CLOSED: knowledge library drift {rel}: expected {expected}, got {actual}")
    actual_gr = sha256_file(GENERIC_RULES_FILE)
    if actual_gr != GENERIC_RULES_SHA:
        raise RuntimeError(f"FAIL-CLOSED: generic rules drift {GENERIC_RULES_FILE}: expected {GENERIC_RULES_SHA}, got {actual_gr}")
    for pname, p in PROJECTS.items():
        snap = load_json(HELDOUT / p["snapshot_file"])
        validate_knowledge_snapshot(snap)
        for rel, _expected in PINNED_KNOWLEDGE_SHA.items():
            stem = rel.removesuffix(".json")
            if json_text(snap[stem]) != json_text(load_json(EXPERIMENTS / rel)):
                raise RuntimeError(f"FAIL-CLOSED: {pname} snapshot embedded {stem} does not match pinned live file")
        intake = load_json(HELDOUT / p["intake_file"])
        if intake["canonical_source"]["commit"] != p["commit"]:
            raise RuntimeError(f"FAIL-CLOSED: {pname} intake commit mismatch")
        if snap["provenance"]["source_commit"] != p["commit"]:
            raise RuntimeError(f"FAIL-CLOSED: {pname} snapshot source_commit mismatch")
        if snap.get("status") != p["snapshot_status"]:
            raise RuntimeError(f"FAIL-CLOSED: {pname} snapshot expected status={p['snapshot_status']}, got {snap.get('status')}")
        if snap.get("full_pre") != p["snapshot_full_pre"]:
            raise RuntimeError(f"FAIL-CLOSED: {pname} snapshot expected full_pre={p['snapshot_full_pre']}, got {snap.get('full_pre')}")
        # Contract edges recorded in the snapshot must be the source of truth for
        # the pool universe; any edge explicitly marked unverified must NOT be used.
        unverified = snap.get("contract", {}).get("unverified_contract_edges") or []
        for ue in unverified:
            for _, _, _, ck in p["edges"]:
                if ck == ue:
                    raise RuntimeError(f"FAIL-CLOSED: {pname} uses unverified contract edge {ue}")
        for f, h in intake["sha256"].items():
            if not h or h in ("unavailable", "unknown"):
                raise RuntimeError(f"FAIL-CLOSED: {pname} intake records unavailable hash for {f}")
    print("Gate 0: snapshots schema-valid; pinned SE/DP/JE + generic-rules hashes intact; commits consistent.")


# --------------------------------------------------------------------------
# Gate 2: candidate pool construction (unchanged byte-identically)
# --------------------------------------------------------------------------

def build_candidates(project_id: str) -> tuple[list[dict[str, Any]], dict[str, tuple[str, str, list[str]]]]:
    """Return (pool candidate records in registration order, classification map).

    classification[candidate_id] = (class, rule_id, evidence_refs)
    Classification is OUT-OF-BAND: it never enters any LLM bundle.
    """
    p = PROJECTS[project_id]
    snap = load_json(HELDOUT / p["snapshot_file"])
    contracts = snap.get("contract", {}).get("contracts", {})
    intake = load_json(HELDOUT / p["intake_file"])
    intake_ref = f"heldout/{p['intake_file']}"
    snap_ref = f"heldout/{p['snapshot_file']}"

    candidates: list[dict[str, Any]] = []
    classification: dict[str, tuple[str, str, list[str]]] = {}

    for family in p["supported_families"]:
        if family == "kill":
            continue
        for edge_key, _src, dst, ck in p["edges"]:
            cid = candidate_id_for_edge(project_id, edge_key, family)
            evidence = [f"{intake_ref}#dependency_graph"]
            if ck:
                evidence.append(f"{snap_ref}#contract/contracts/{ck}")
            candidates.append({
                "candidate_id": cid,
                "project_id": project_id,
                "workload_id": f"{project_id}/{edge_key}",
                "target": dst,
                "fault_family": family,
                "fault_parameters": {"mode": family, "scope": "service_edge"},
                "mutation_path": None,
                "static_evidence_refs": evidence,
                "information_tier": ["I0", "I1-local"],
                "oracle_label": "stored-out-of-band",
            })
            meta = contracts.get(ck) if ck else None
            classification[cid] = classify_edge(family, meta, evidence)

    if p["kill"]["available"]:
        avail = snap.get("contract", {}).get("availability_kubernetes", {}).get(project_id, {})
        for svc in p["kill_targets"]:
            cid = candidate_id_for_kill(project_id, svc)
            candidates.append({
                "candidate_id": cid,
                "project_id": project_id,
                "workload_id": f"{project_id}/{svc}-pod",
                "target": svc,
                "fault_family": "kill",
                "fault_parameters": {"mode": "kill", "scope": "pod"},
                "mutation_path": None,
                "static_evidence_refs": [f"{snap_ref}#contract/availability_kubernetes"],
                "information_tier": ["I0", "I1-local"],
                "oracle_label": "stored-out-of-band",
            })
            meta = avail.get(svc, {})
            replicas = meta.get("replicas")
            pdb = meta.get("pdb")
            if isinstance(replicas, int) and replicas >= 2:
                classification[cid] = ("protected", "CLS-004",
                                       [f"{snap_ref}#contract/availability_kubernetes/{svc}"])
            elif replicas == 1 and pdb in (None, False, 0):
                classification[cid] = ("unprotected", "CLS-004",
                                       [f"{snap_ref}#contract/availability_kubernetes/{svc}"])
            else:
                classification[cid] = ("unknown", "CLS-004",
                                       [f"{snap_ref}#contract/availability_kubernetes/{svc}"])

    return candidates, classification


def classify_edge(family: str, meta: dict[str, Any] | None, evidence: list[str]) -> tuple[str, str, list[str]]:
    if meta is None:
        return ("unknown", "CLS-005", evidence)
    contract = meta.get("contract")
    if contract == "no_timeout":
        return ("unprotected", "CLS-003", evidence)
    if contract == "explicit_timeout":
        if family == "delay":
            return ("protected", "CLS-002", evidence)
        if meta.get("loss_bounded"):
            return ("protected", "CLS-001", evidence)
        return ("unprotected", "CLS-002", evidence)
    return ("unknown", "CLS-005", evidence)


def pool_quota_fill(all_candidates: list[dict[str, Any]], phase: str, project_id: str) -> list[dict[str, Any]]:
    """Fill the phase pool by fixed family rotation (pre-registered rule).

    Pilot per-family target 8, formal 16; when fewer families are supported the
    same rotation fills the total pool size; remaining capacity is distributed
    round-robin across supported families so a shortfall in one family is never
    silently rebalanced away.
    """
    p = PROJECTS[project_id]
    families = p["supported_families"]
    size = POOL_SIZE[phase]
    per_family = size // len(families) if families else 0
    by_family: dict[str, list[dict[str, Any]]] = {f: [] for f in families}
    for c in all_candidates:
        by_family.setdefault(c["fault_family"], []).append(c)
    chosen: list[dict[str, Any]] = []
    chosen_ids: set[str] = set()
    for f in families:
        for c in by_family[f][:per_family]:
            chosen.append(c)
            chosen_ids.add(c["candidate_id"])
    remaining = size - len(chosen)
    rounds = 0
    while remaining > 0 and rounds < 100:
        for f in families:
            if remaining <= 0:
                break
            for c in by_family[f][per_family:]:
                if c["candidate_id"] not in chosen_ids:
                    chosen.append(c)
                    chosen_ids.add(c["candidate_id"])
                    remaining -= 1
                    break
        rounds += 1
    return chosen


def composition_summary(pool: list[dict[str, Any]], classification: dict[str, tuple[str, str, list[str]]]) -> dict[str, Any]:
    counts = {"protected": 0, "unprotected": 0, "unknown": 0}
    by_family: dict[str, int] = {}
    for c in pool:
        cls = classification.get(c["candidate_id"], ("unknown", "?", []))[0]
        counts[cls] += 1
        by_family[c["fault_family"]] = by_family.get(c["fault_family"], 0) + 1
    return {"total": len(pool), "protected": counts["protected"],
            "unprotected": counts["unprotected"], "unknown": counts["unknown"],
            "by_family": by_family}


# --------------------------------------------------------------------------
# Gate 1: arm views (Fix 1: generic view = curated generic-rules-only)
# --------------------------------------------------------------------------

def build_arm_views(project_id: str) -> dict[str, dict[str, Any]]:
    p = PROJECTS[project_id]
    snap = load_json(HELDOUT / p["snapshot_file"])
    generic_rules = load_json(ROOT / GENERIC_RULES_FILE)

    third_key = p["third_arm"]["view_key"]
    third = {
        "snapshot_id": f"{project_id}-{third_key}-2026-08-10",
        "arm_id": p["third_arm"]["id"],
        "full_pre_claimable": p["third_arm"]["full_pre_claimable"],
        "claim_reason": p["third_arm"]["reason"],
        "provenance": snap["provenance"],
        "contract": {"contracts": snap["contract"]["contracts"]},
        "availability_scope": snap["availability_scope"],
        "source_provenance": snap["source_provenance"],
        "generic_rules": {
            "selection_experience": generic_rules["selection_experience"],
            "defense_pattern_library": generic_rules["defense_pattern_library"],
            "judgment_experience": generic_rules["judgment_experience"],
            "generic_rules_file": GENERIC_RULES_FILE,
            "generic_rules_sha256": GENERIC_RULES_SHA,
        },
        "redacted_fields": ["status", "status_reason", "contract.availability",
                            "contract.availability_kubernetes", "contract.candidate_map",
                            "full_pre", "selection_experience_raw", "defense_pattern_library_raw",
                            "judgment_experience_raw"],
    }
    generic = {
        "snapshot_id": f"{project_id}-generic-2026-08-10",
        "generic_rules": {
            "selection_experience": generic_rules["selection_experience"],
            "defense_pattern_library": generic_rules["defense_pattern_library"],
            "judgment_experience": generic_rules["judgment_experience"],
            "generic_rules_file": GENERIC_RULES_FILE,
            "generic_rules_sha256": GENERIC_RULES_SHA,
        },
        "redacted_fields": ["contract", "availability_scope", "source_provenance",
                            "provenance", "status", "status_reason",
                            "selection_experience_raw", "defense_pattern_library_raw",
                            "judgment_experience_raw"],
        "provenance_note": ("generic-rules-only view distilled from the pinned SE/DP/JE via "
                            "knowledge_ablation_generic_rules_v1.json; all historical project names, "
                            "service names, candidate IDs, evidence fields, file paths and project "
                            "results are removed (Fix 1)."),
    }
    blind = {
        "snapshot_id": f"{project_id}-blind-2026-08-10",
        "knowledge": "none",
        "redacted_fields": ["contract", "availability_scope", "source_provenance",
                            "provenance", "generic_rules", "selection_experience",
                            "defense_pattern_library", "judgment_experience",
                            "status", "status_reason"],
    }
    return {"blind": blind, "generic": generic, third_key: third}


# --------------------------------------------------------------------------
# Prompt templates (identical across arms except the knowledge supplement line)
# --------------------------------------------------------------------------

OUTPUT_SCHEMA = {
    "type": "object",
    "properties": {
        "selected": {
            "type": "array",
            "description": "exactly K entries, ranks 1..K, all candidate_id in the pool, no duplicates",
            "items": {
                "type": "object",
                "properties": {
                    "candidate_id": {"type": "string"},
                    "rank": {"type": "integer"},
                    "rationale": {"type": "string"},
                },
                "required": ["candidate_id", "rank", "rationale"],
            },
        }
    },
    "required": ["selected"],
}

TASK_DEFINITION = {
    "study": "LLM knowledge-base ablation (protocol v1): quantify the causal contribution "
             "of a frozen knowledge base to LLM test-node (fault-injection candidate) selection.",
    "unit_of_analysis": "project x candidate_pool x arm x seed",
    "task": ("Rank the most impactful fault-injection candidates from the frozen pool, where "
             "impactful means most likely to expose a confirmed weakness of the system under test "
             "(e.g., unbounded latency propagation, missing timeout/retry defenses, availability "
             "loss, or missing recovery)."),
    "constraints": [
        "select exactly K distinct candidates",
        "select only candidate IDs present in the pool; never invent candidates",
        "rank selected candidates from most to least impactful",
        "one short rationale (<=2 sentences) per selected candidate",
        "reply with a single JSON object matching the output schema",
    ],
    "forbidden_inputs_for_llm": [
        "oracle labels", "post-hoc runtime outcomes", "other arms' outputs",
        "previous method rankings", "truth labels",
    ],
}

SYSTEM_TEMPLATE = """\
You are a senior chaos-engineering analyst participating in a fault-injection candidate-selection study. You will be given a frozen candidate pool for a microservice system. Each candidate is one fault injection targeting a specific service or service-to-service edge with one fault family (delay, loss, or kill).

Your task is to select exactly {k} candidates from the pool that are most likely to expose a confirmed weakness of the system under test (for example: unbounded latency propagation, missing timeout or retry defenses, availability loss, or missing recovery behavior).

Rules:
- Select exactly {k} distinct candidates.
- Select only candidates present in the pool; never invent candidates.
- Rank the selected candidates from most to least impactful.
- Provide a short rationale (at most two sentences) per selected candidate, naming the expected failure mechanism and the affected service/edge.
{knowledge_line}
Reply with a single JSON object and nothing else (no markdown). Output schema:
{format_schema}
"""

KNOWLEDGE_LINE = {
    "LLM-blind": "",
    "LLM-generic": "A generic-rules-only knowledge supplement (selection rules, defense patterns, and judgment experience, project-free) is provided in the user message for your reference.\n",
    "LLM-full-pre": "A generic-rules-only knowledge supplement and a project-specific pre-experiment snapshot (static contracts, availability scope, source provenance) are provided in the user message for your reference.\n",
    "LLM-partial-pre": "A generic-rules-only knowledge supplement and a project-specific partial pre-experiment snapshot (static contracts where verified; availability unavailable) are provided in the user message for your reference.\n",
}

USER_TEMPLATE = """\
PROJECT UNDER TEST - INTAKE SUMMARY
{intake_json}

CANDIDATE POOL ({n} candidates, in the order given)
{pool_json}

{knowledge_block}TASK
Rank exactly {k} distinct candidates from the pool, from most to least likely to expose a confirmed weakness, and return them as a single JSON object following the output schema in the system message.
"""


def neutral_intake_summary(project_id: str, include_availability: bool) -> dict[str, Any]:
    """Neutral project intake summary for the blind/generic arms (no contract or
    availability facts); the third arm adds availability scope and source provenance."""
    p = PROJECTS[project_id]
    snap = load_json(HELDOUT / p["snapshot_file"])
    intake = load_json(HELDOUT / p["intake_file"])
    summary: dict[str, Any] = {
        "project_id": project_id,
        "tech_stack": intake["canonical_source"]["tech_stack"],
        "services": intake["services"],
        "call_edges": [e[0] for e in p["edges"]],
        "observability": p["observability_neutral"],
        "workload": p["workload_neutral"],
    }
    if include_availability:
        summary["source_commit"] = p["commit"]
        summary["availability_scope"] = p["availability_scope"]
        summary["source_provenance"] = snap["source_provenance"]
    return summary


def neutral_descriptors(pool: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """LLM-facing neutral descriptors: no static_evidence_refs, no oracle_label,
    no contract/availability facts."""
    out = []
    for c in pool:
        out.append({
            "candidate_id": c["candidate_id"],
            "project_id": c["project_id"],
            "workload_id": c["workload_id"],
            "target": c["target"],
            "fault_family": c["fault_family"],
            "fault_parameters": c["fault_parameters"],
            "mutation_path": c["mutation_path"],
        })
    return out


def generic_rules_block(gr: dict[str, Any]) -> str:
    return json_text({"selection_experience": gr["selection_experience"],
                      "defense_pattern_library": gr["defense_pattern_library"],
                      "judgment_experience": gr["judgment_experience"]})


def knowledge_block(arm: str, views: dict[str, dict[str, Any]], project_id: str) -> str:
    if arm == "LLM-blind":
        return ""
    p = PROJECTS[project_id]
    third_key = p["third_arm"]["view_key"]
    gr = views["generic"]["generic_rules"]
    parts = ["GENERIC RULES-ONLY SUPPLEMENT (project-free, pinned frozen version)\n" + generic_rules_block(gr)]
    if arm in ("LLM-full-pre", "LLM-partial-pre"):
        third = views[third_key]
        parts.append("PROJECT-SPECIFIC PRE-EXPERIMENT SNAPSHOT (static contracts, availability scope, "
                     "source provenance; no runtime outcomes)\n" +
                     json_text({"provenance": third["provenance"],
                                "contract": third["contract"],
                                "availability_scope": third["availability_scope"],
                                "source_provenance": third["source_provenance"]}))
    return "\n\n".join(parts) + "\n\n"


# --------------------------------------------------------------------------
# Leakage audit (Fix 4: historical + current + evidence markers)
# --------------------------------------------------------------------------

def run_leakage_audit(project_id: str, phase: str, arm: str, bundle: dict[str, Any],
                      prompt_text: str) -> dict[str, Any]:
    p = PROJECTS[project_id]
    sections = bundle["sections"]
    results: dict[str, Any] = {"project": project_id, "phase": phase, "arm": arm, "scans": []}

    results["whole_bundle_forbidden_fields"] = find_forbidden_fields(bundle, FORBIDDEN_FIELDS)

    def scan(name: str, text: str, terms: list[str], obj: Any = None, fields: list[str] | None = None) -> None:
        hits = scan_terms(text, terms)
        field_hits = find_forbidden_fields(obj, fields) if obj is not None else []
        results["scans"].append({"section": name, "term_hits": hits, "forbidden_fields": field_hits})

    # Every arm: descriptors must be neutral (no oracle/evidence fields, no
    # historical terms, no narrow markers).
    scan("candidate_descriptors", json_text(sections["candidate_descriptors"]),
         HISTORICAL_TERMS + NARROW_MARKERS, sections["candidate_descriptors"], FORBIDDEN_FIELDS)

    if arm == "LLM-blind":
        assert sections["knowledge"] is None, "blind arm must carry no knowledge"
        scan("knowledge", "", CONTRACT_TERMS + AVAILABILITY_TERMS + KNOWLEDGE_MARKERS +
             PROJECT_TERMS[project_id] + HISTORICAL_TERMS + NARROW_MARKERS)
        scan("project_intake_summary", json_text(sections["project_intake_summary"]),
             CONTRACT_TERMS + AVAILABILITY_TERMS + KNOWLEDGE_MARKERS + HISTORICAL_TERMS + NARROW_MARKERS)
    elif arm == "LLM-generic":
        assert sections["knowledge"] is not None
        scan("knowledge", json_text(sections["knowledge"]),
             PROJECT_TERMS[project_id] + HISTORICAL_TERMS + NARROW_MARKERS + EVIDENCE_MARKERS,
             sections["knowledge"], FORBIDDEN_FIELDS)
        scan("project_intake_summary", json_text(sections["project_intake_summary"]),
             CONTRACT_TERMS + AVAILABILITY_TERMS + KNOWLEDGE_MARKERS + HISTORICAL_TERMS + NARROW_MARKERS)
    else:  # LLM-full-pre / LLM-partial-pre
        k = sections["knowledge"]
        assert isinstance(k, dict) and "generic_rules" in k and "project_specific" in k
        scan("knowledge.generic_rules", json_text(k["generic_rules"]),
             PROJECT_TERMS[project_id] + HISTORICAL_TERMS + NARROW_MARKERS + EVIDENCE_MARKERS,
             k["generic_rules"], FORBIDDEN_FIELDS)
        scan("knowledge.project_specific", json_text(k["project_specific"]),
             HISTORICAL_TERMS + NARROW_MARKERS, k["project_specific"], FORBIDDEN_FIELDS)
        scan("project_intake_summary", json_text(sections["project_intake_summary"]),
             HISTORICAL_TERMS + NARROW_MARKERS)

    scan("rendered_prompt", prompt_text, HISTORICAL_TERMS + NARROW_MARKERS)
    ok = (not results["whole_bundle_forbidden_fields"]
          and all(not e["term_hits"] and not e["forbidden_fields"] for e in results["scans"]))
    results["pass"] = ok
    return results


# --------------------------------------------------------------------------
# Fix 7: mutation YAML generation + candidate_id -> mutation_path mapping
# --------------------------------------------------------------------------

def mutation_yaml(candidate: dict[str, Any], namespace: str) -> str:
    fam = candidate["fault_family"]
    meta = MUTATION_PARAMS[fam]
    name = f"eval-{candidate['candidate_id'].lower()}"
    if fam == "kill":
        return (
            f"apiVersion: chaos-mesh.org/v1alpha1\n"
            f"kind: PodChaos\n"
            f"metadata:\n"
            f"  name: {name}\n"
            f"  namespace: {namespace}\n"
            f"  labels:\n"
            f"    chaos.evaluation: track-k\n"
            f"spec:\n"
            f"  action: pod-kill\n"
            f"  mode: one\n"
            f"  selector:\n"
            f"    namespaces:\n"
            f"      - {namespace}\n"
            f"    labelSelectors:\n"
            f"      app: {candidate['target']}\n"
            f"  duration: \"{meta['duration']}\"\n"
        )
    body = (
        f"apiVersion: chaos-mesh.org/v1alpha1\n"
        f"kind: NetworkChaos\n"
        f"metadata:\n"
        f"  name: {name}\n"
        f"  namespace: {namespace}\n"
        f"  labels:\n"
        f"    chaos.evaluation: track-k\n"
        f"spec:\n"
        f"  action: {meta['action']}\n"
        f"  mode: one\n"
        f"  selector:\n"
        f"    namespaces:\n"
        f"      - {namespace}\n"
        f"    labelSelectors:\n"
        f"      app: {candidate['target']}\n"
    )
    if fam == "delay":
        body += (f"  delay:\n"
                 f"    latency: \"{meta['latency']}\"\n"
                 f"    correlation: \"{meta['correlation']}\"\n"
                 f"    jitter: \"{meta['jitter']}\"\n")
    else:  # loss
        body += (f"  loss:\n"
                 f"    loss: \"{meta['loss']}\"\n"
                 f"    correlation: \"{meta['correlation']}\"\n")
    body += (f"  duration: \"{meta['duration']}\"\n"
             f"  direction: {meta['direction']}\n")
    return body


# --------------------------------------------------------------------------
# Main
# --------------------------------------------------------------------------

def main() -> int:
    protocol_sha = sha256_file("artifacts/experiments/llm_knowledge_ablation_protocol_v1.md")
    verify_gate0(protocol_sha)

    planned_files: set[Path] = set()
    file_hashes: dict[str, str] = {}
    audit_entries: list[dict[str, Any]] = []
    pool_compositions: dict[str, dict[str, Any]] = {}
    prompt_hashes: dict[str, dict[str, dict[str, str]]] = {}
    formal_conformance: dict[str, dict[str, Any]] = {}

    for pname in PROJECTS:
        p = PROJECTS[pname]
        views = build_arm_views(pname)
        candidates, classification = build_candidates(pname)
        intake = load_json(HELDOUT / p["intake_file"])
        snap = load_json(HELDOUT / p["snapshot_file"])
        third_key = p["third_arm"]["view_key"]
        arms = ("LLM-blind", "LLM-generic", p["third_arm"]["id"])
        arm_dirs = {"LLM-blind": "blind", "LLM-generic": "generic",
                    "LLM-full-pre": "full-pre", "LLM-partial-pre": "partial-pre"}

        # ---- Gate 2: pools (byte-identical to the frozen pools) ----
        pools: dict[str, list[dict[str, Any]]] = {}
        pool_file_hashes: dict[str, str] = {}
        for phase in ("pilot", "formal"):
            pool = pool_quota_fill(candidates, phase, pname)
            pools[phase] = pool
            pool_obj = {
                "schema_version": 1,
                "purpose": "ablation protocol v1 sections 4-5: method-neutral candidate pool",
                "protocol_sha256": protocol_sha,
                "project_id": pname,
                "phase": phase,
                "selection_budget_k": BUDGET_K[phase],
                "pool_size_target": POOL_SIZE[phase],
                "pool_size_actual": len(pool),
                "pool_size_deviation": len(pool) - POOL_SIZE[phase],
                "pool_size_deviation_reason": ("verified-universe shortfall: the pool is built only from "
                                               "statically-documented call edges (intake dependency graph) and "
                                               "helm-verified kill targets at the frozen commit; no candidates are "
                                               "borrowed and none are invented to reach the target"),
                "pool_construction_rule": POOL_CONSTRUCTION_RULE,
                "supported_fault_families": p["supported_families"],
                "kill_family": {"available": p["kill"]["available"], "reason": p["kill"]["reason"]},
                "candidates": pool,
                "protection_note": ("protection classes and quota compliance are recorded out-of-band in "
                                    "knowledge_ablation_oracle/<project>/candidate_protection_classification.json; "
                                    "oracle_label is a placeholder only - real labels live out-of-band."),
            }
            rel = f"artifacts/experiments/knowledge_ablation_candidates/{pname}/{phase}.json"
            path = EXPERIMENTS / f"knowledge_ablation_candidates/{pname}/{phase}.json"
            planned_files.add(path)
            if path.exists():
                raise RuntimeError(f"FAIL-CLOSED: refusing to overwrite existing {rel}")
            write_json(path, pool_obj)
            file_hashes[rel] = sha256_file(rel)
            pool_file_hashes[phase] = file_hashes[rel]
            pool_compositions[f"{pname}/{phase}"] = composition_summary(pool, classification)
            # Fix 6: record formal-48 conformance (declaration only; pool bytes unchanged).
            formal_conformance[f"{pname}/{phase}"] = {
                "pool_size_target": POOL_SIZE[phase],
                "pool_size_actual": len(pool),
                "deviation": len(pool) - POOL_SIZE[phase],
                "conforms_to_preregistered_size": len(pool) == POOL_SIZE[phase],
                "usable_as_preregistered_formal_48": (phase != "formal" or len(pool) == POOL_SIZE[phase]),
                "requires_protocol_amendment": (phase == "formal" and len(pool) != POOL_SIZE[phase]),
                "note": ("a formal pool smaller than the pre-registered 48 cannot be used as the "
                         "pre-registered formal-48 pool without a protocol amendment; no amendment is "
                         "claimed in this package." if (phase == "formal" and len(pool) != POOL_SIZE[phase])
                         else "pool matches the pre-registered size."),
            }

        # ---- Out-of-band classification ----
        cls_out: dict[str, dict[str, Any]] = {}
        for cid, (cls, rule, ev) in classification.items():
            cls_out[cid] = {"class": cls, "classification_rule": rule, "evidence_refs": ev}
        quota = {}
        for phase in ("pilot", "formal"):
            comp = pool_compositions[f"{pname}/{phase}"]
            tgt = PROTECTION_QUOTA[phase]
            quota[phase] = {
                "actual": {"protected": comp["protected"], "unprotected": comp["unprotected"], "unknown": comp["unknown"]},
                "target": {"protected": tgt[0], "unprotected": tgt[1], "unknown": tgt[2]},
                "deviations": {
                    "protected": comp["protected"] - tgt[0],
                    "unprotected": comp["unprotected"] - tgt[1],
                    "unknown": comp["unknown"] - tgt[2],
                },
            }
        classification_file = {
            "kind": "static_pre_selection_classification",
            "scope_note": ("Static evidence classification only, built under pre-registered rules CLS-001..CLS-005. "
                           "Runtime weakness oracle is deferred until after selection (ablation protocol section 7) "
                           "and is not part of this file."),
            "protocol_sha256": protocol_sha,
            "classification_rules": CLASSIFICATION_RULES,
            "pool_construction_rule": POOL_CONSTRUCTION_RULE,
            "classifications": cls_out,
            "quota_compliance": quota,
            "exposure": "out_of_band - included in NO LLM bundle",
        }
        rel_cls = f"artifacts/experiments/knowledge_ablation_oracle/{pname}/candidate_protection_classification.json"
        path_cls = EXPERIMENTS / f"knowledge_ablation_oracle/{pname}/candidate_protection_classification.json"
        planned_files.add(path_cls)
        if path_cls.exists():
            raise RuntimeError(f"FAIL-CLOSED: refusing to overwrite existing {rel_cls}")
        write_json(path_cls, classification_file)
        file_hashes[rel_cls] = sha256_file(rel_cls)

        # ---- Fix 7: mutation YAML + mapping (pools keep mutation_path=null) ----
        mutation_dir = EXPERIMENTS / f"knowledge_ablation_mutations/{pname}"
        mutation_map_entries: dict[str, dict[str, Any]] = {}
        for phase in ("pilot", "formal"):
            for c in pools[phase]:
                rel_yaml = f"artifacts/experiments/knowledge_ablation_mutations/{pname}/{c['candidate_id']}.yaml"
                path_yaml = EXPERIMENTS / f"knowledge_ablation_mutations/{pname}/{c['candidate_id']}.yaml"
                if c["candidate_id"] in mutation_map_entries:
                    # Same candidate appears in both pilot and formal pools: the
                    # mutation YAML is generated once; eligibility accumulates.
                    mutation_map_entries[c["candidate_id"]]["pool_eligibility"].append(phase)
                    continue
                planned_files.add(path_yaml)
                if path_yaml.exists():
                    raise RuntimeError(f"FAIL-CLOSED: refusing to overwrite existing {rel_yaml}")
                path_yaml.parent.mkdir(parents=True, exist_ok=True)
                path_yaml.write_text(mutation_yaml(c, f"heldout-{pname.lower()}-lab"), encoding="utf-8")
                file_hashes[rel_yaml] = sha256_file(rel_yaml)
                mutation_map_entries[c["candidate_id"]] = {
                    "candidate_id": c["candidate_id"],
                    "fault_family": c["fault_family"],
                    "target": c["target"],
                    "mode": "one",
                    "mutation_path": rel_yaml,
                    "yaml_sha256": file_hashes[rel_yaml],
                    "fault_parameters": MUTATION_PARAMS[c["fault_family"]],
                    "pool_eligibility": [phase],
                }
        mutation_map = {
            "schema_version": 1,
            "purpose": "ablation protocol v1 fix 7: independent candidate_id -> mutation_path mapping "
                       "(frozen candidate pools are NOT modified; their mutation_path stays null)",
            "protocol_sha256": protocol_sha,
            "project_id": pname,
            "namespace": f"heldout-{pname.lower()}-lab (pre-registered placeholder; confirm at deployment gate)",
            "mutation_directory": f"artifacts/experiments/knowledge_ablation_mutations/{pname}/",
            "parameter_tiers": MUTATION_PARAMS,
            "entries": mutation_map_entries,
            "status": "frozen_pre_registered_not_yet_executed",
        }
        rel_mm = f"artifacts/experiments/knowledge_ablation_mutations/{pname}/mutation_map.json"
        path_mm = EXPERIMENTS / f"knowledge_ablation_mutations/{pname}/mutation_map.json"
        planned_files.add(path_mm)
        if path_mm.exists():
            raise RuntimeError(f"FAIL-CLOSED: refusing to overwrite existing {rel_mm}")
        write_json(path_mm, mutation_map)
        file_hashes[rel_mm] = sha256_file(rel_mm)

        # ---- Gate 0/1: commit manifest, snapshot manifest, arm views ----
        commit_manifest = {
            "schema_version": 1,
            "purpose": "ablation protocol v1 section 4 item 1",
            "protocol_sha256": protocol_sha,
            "project_id": pname,
            "canonical_url": p["canonical_url"],
            "commit": p["commit"],
            "branch_or_tag": p["ref"],
            "license": p["license"],
            "source_path_outside_repository": p["source_path"],
            "source_file_sha256": intake["sha256"],
            "hash_verification": {
                "status": "recorded_2026-08-10_intake_not_reverified_this_session",
                "note": ("WSL checkout under /root/heldout_src is root-owned and not readable in this session "
                         "(no interactive sudo); hashes are the frozen intake values. Independent re-verification "
                         "requires a human with WSL root access."),
            },
            "snapshot_reference": {"file": f"heldout/{p['snapshot_file']}",
                                   "sha256": sha256_file(f"artifacts/experiments/heldout/{p['snapshot_file']}")},
            "tooling": {"repo_head": "8209ee9",
                        "repo_note": "working tree carries uncommitted held-out stage artifacts; no ablation "
                                     "artifact was committed in this run"},
        }
        # Fix 2: full_pre/status read from the LIVE snapshot (not hardcoded).
        snap_manifest = {
            "schema_version": 1,
            "purpose": "ablation protocol v1 section 4 item 2",
            "protocol_sha256": protocol_sha,
            "project_id": pname,
            "snapshots": {
                "original": {
                    "id": f"{pname}-pre-2026-08-10",
                    "file": f"heldout/{p['snapshot_file']}",
                    "sha256": sha256_file(f"artifacts/experiments/heldout/{p['snapshot_file']}"),
                    "created_at": snap["provenance"]["created_at"],
                    "source_provenance": snap["source_provenance"],
                    "status": snap.get("status"),
                    "full_pre": snap.get("full_pre"),
                    "provenance_completeness": snap["provenance"].get("provenance_completeness"),
                    "allowed_fields": ["contract", "availability_scope", "source_provenance",
                                       "selection_experience", "defense_pattern_library",
                                       "judgment_experience", "provenance"],
                    "redacted_fields": ["status", "status_reason", "contract.availability",
                                        "contract.availability_kubernetes", "contract.candidate_map",
                                        "full_pre"],
                },
                "arm_views": {},
            },
            "generic_rules": {"file": GENERIC_RULES_FILE, "sha256": GENERIC_RULES_SHA,
                              "note": "generic-rules-only distilled knowledge used by LLM-generic and "
                                      "the project-specific-pre arm (Fix 1)"},
            "pinned_knowledge_sha256": PINNED_KNOWLEDGE_SHA,
        }
        for arm_key, arm_id in (("blind", "LLM-blind"), ("generic", "LLM-generic"), (third_key, p["third_arm"]["id"])):
            rel_view = f"artifacts/experiments/knowledge_ablation_snapshots/{pname}/{arm_key}_view.json"
            path_view = EXPERIMENTS / f"knowledge_ablation_snapshots/{pname}/{arm_key}_view.json"
            planned_files.add(path_view)
            if path_view.exists():
                raise RuntimeError(f"FAIL-CLOSED: refusing to overwrite existing {rel_view}")
            write_json(path_view, views[arm_key])
            file_hashes[rel_view] = sha256_file(rel_view)
            snap_manifest["snapshots"]["arm_views"][arm_key] = {
                "arm_id": arm_id,
                "file": rel_view,
                "sha256": file_hashes[rel_view],
                "allowed_fields": sorted(views[arm_key].keys()),
                "redacted_fields": views[arm_key]["redacted_fields"],
            }

        # ---- Prompts: bundles, rendered per-seed prompts, manifest ----
        bundles: dict[str, dict[str, dict[str, Any]]] = {}
        for arm in arms:
            bundles[arm] = {}
            for phase in ("pilot", "formal"):
                pool = pools[phase]
                k = BUDGET_K[phase]
                include_avail = arm in ("LLM-full-pre", "LLM-partial-pre")
                intake_summary = neutral_intake_summary(pname, include_avail)
                descs = neutral_descriptors(pool)
                kb = knowledge_block(arm, views, pname)
                knowledge = None
                if arm == "LLM-generic":
                    knowledge = {"generic_rules": views["generic"]["generic_rules"]}
                elif arm in ("LLM-full-pre", "LLM-partial-pre"):
                    third = views[third_key]
                    knowledge = {
                        "generic_rules": views["generic"]["generic_rules"],
                        "project_specific": {
                            "provenance": third["provenance"],
                            "contract": third["contract"],
                            "availability_scope": third["availability_scope"],
                            "source_provenance": third["source_provenance"],
                        },
                    }
                bundle = {
                    "arm_id": arm,
                    "project_id": pname,
                    "phase": phase,
                    "protocol_sha256": protocol_sha,
                    "model_identifier": LLM_CONFIG["model_identifier"],
                    "endpoint": LLM_CONFIG["endpoint"],
                    "temperature": LLM_CONFIG["temperature"],
                    "max_output_tokens": LLM_CONFIG["max_output_tokens"],
                    "timeout_seconds": LLM_CONFIG["timeout_seconds"],
                    "selection_budget_k": k,
                    "candidate_pool_sha256": pool_file_hashes[phase],
                    "sections": {
                        "task_definition": TASK_DEFINITION,
                        "project_intake_summary": intake_summary,
                        "candidate_descriptors": descs,
                        "knowledge": knowledge,
                    },
                }
                bundles[arm][phase] = bundle

                system = SYSTEM_TEMPLATE.format(k=k, knowledge_line=KNOWLEDGE_LINE[arm],
                                                format_schema=json_text(OUTPUT_SCHEMA))
                for seed in SEEDS[phase]:
                    order = seeded_permutation(len(descs), seed)
                    permuted = [descs[i] for i in order]
                    user = USER_TEMPLATE.format(intake_json=json_text(intake_summary),
                                                n=len(descs), pool_json=json_text(permuted),
                                                knowledge_block=kb, k=k)
                    prompt_text = f"{system}\n\n===== USER =====\n{user}"
                    arm_dir = arm_dirs[arm]
                    prompt_rel = (f"artifacts/experiments/knowledge_ablation_prompts/{pname}/"
                                  f"{arm_dir}/{phase}/seed-{seed}.prompt.txt")
                    path_prompt = EXPERIMENTS / f"knowledge_ablation_prompts/{pname}/{arm_dir}/{phase}/seed-{seed}.prompt.txt"
                    planned_files.add(path_prompt)
                    if path_prompt.exists():
                        raise RuntimeError(f"FAIL-CLOSED: refusing to overwrite existing {prompt_rel}")
                    path_prompt.parent.mkdir(parents=True, exist_ok=True)
                    path_prompt.write_text(prompt_text, encoding="utf-8")
                    file_hashes[prompt_rel] = sha256_file(prompt_rel)
                    prompt_hashes.setdefault(pname, {}).setdefault(arm, {})[f"{phase}/{seed}"] = prompt_rel
                    audit_entries.append({"project": pname, "phase": phase, "arm": arm,
                                          "bundle": bundle, "prompt_text": prompt_text,
                                          "prompt_rel": prompt_rel})

        # ---- Write bundles ----
        for arm in arms:
            for phase in ("pilot", "formal"):
                arm_dir = arm_dirs[arm]
                rel = f"artifacts/experiments/knowledge_ablation_prompts/{pname}/{arm_dir}/{phase}/bundle.json"
                path = EXPERIMENTS / f"knowledge_ablation_prompts/{pname}/{arm_dir}/{phase}/bundle.json"
                planned_files.add(path)
                if path.exists():
                    raise RuntimeError(f"FAIL-CLOSED: refusing to overwrite existing {rel}")
                write_json(path, bundles[arm][phase])
                file_hashes[rel] = sha256_file(rel)

        # ---- Leakage audit ----
        audit = {"project": pname, "protocol_sha256": protocol_sha,
                 "arm_scans": [], "reviewer_decision": "pending_human_review"}
        for entry in audit_entries:
            if entry["project"] != pname:
                continue
            ar = run_leakage_audit(pname, entry["phase"], entry["arm"], entry["bundle"], entry["prompt_text"])
            ar["prompt_file"] = entry["prompt_rel"]
            audit["arm_scans"].append(ar)
        for phase in ("pilot", "formal"):
            pool_obj = load_json(EXPERIMENTS / f"knowledge_ablation_candidates/{pname}/{phase}.json")
            audit["pool_checks_" + phase] = {
                "narrow_marker_hits": scan_terms(json_text(pool_obj), NARROW_MARKERS),
                "historical_term_hits": scan_terms(json_text(pool_obj), HISTORICAL_TERMS),
                "oracle_label_values": sorted({c.get("oracle_label") for c in pool_obj["candidates"]}),
                "any_real_label": any(c.get("oracle_label") != "stored-out-of-band" for c in pool_obj["candidates"]),
                "mutation_paths_all_null": all(c.get("mutation_path") is None for c in pool_obj["candidates"]),
            }
        # Generic-rules scan: only the LLM-facing rule sections must be clean of
        # historical + current project terms and evidence markers. The top-level
        # provenance metadata (sanitization_log etc.) legitimately documents what
        # was removed and is never sent to any LLM, so it is scanned separately
        # as an informational record, not as a pass/fail gate.
        gr_obj = load_json(ROOT / GENERIC_RULES_FILE)
        gr_sections_text = json_text({k: gr_obj[k] for k in ("selection_experience", "defense_pattern_library", "judgment_experience")})
        gr_meta_text = json_text({k: v for k, v in gr_obj.items() if k not in ("selection_experience", "defense_pattern_library", "judgment_experience")})
        audit["generic_rules_file_scan"] = {
            "llm_facing_sections": {
                "historical_term_hits": scan_terms(gr_sections_text, HISTORICAL_TERMS),
                "evidence_marker_hits": scan_terms(gr_sections_text, EVIDENCE_MARKERS),
                "pass": (not scan_terms(gr_sections_text, HISTORICAL_TERMS)
                         and not scan_terms(gr_sections_text, EVIDENCE_MARKERS)),
            },
            "provenance_metadata_scan": {
                "note": "informational only - metadata documents what was stripped; never sent to any LLM",
                "historical_term_hits": scan_terms(gr_meta_text, HISTORICAL_TERMS),
            },
        }
        rel_audit = f"artifacts/experiments/knowledge_ablation_snapshots/{pname}/leakage_audit.json"
        path_audit = EXPERIMENTS / f"knowledge_ablation_snapshots/{pname}/leakage_audit.json"
        planned_files.add(path_audit)
        if path_audit.exists():
            raise RuntimeError(f"FAIL-CLOSED: refusing to overwrite existing {rel_audit}")
        write_json(path_audit, audit)
        file_hashes[rel_audit] = sha256_file(rel_audit)

        # ---- Prompt manifest ----
        arm_prompt_summary: dict[str, Any] = {}
        for arm in arms:
            arm_prompt_summary[arm] = {}
            for phase in ("pilot", "formal"):
                arm_prompt_summary[arm][phase] = {}
                for seed in SEEDS[phase]:
                    prompt_rel = prompt_hashes[pname][arm][f"{phase}/{seed}"]
                    arm_prompt_summary[arm][phase][str(seed)] = {"file": prompt_rel, "sha256": file_hashes[prompt_rel]}
        permutations = {phase: {str(s): seeded_permutation(len(pools[phase]), s) for s in SEEDS[phase]}
                        for phase in ("pilot", "formal")}
        prompt_manifest = {
            "schema_version": 1,
            "purpose": "ablation protocol v1 section 4 item 4: prompt pre-registration",
            "protocol_sha256": protocol_sha,
            "project_id": pname,
            "model_identifier": LLM_CONFIG["model_identifier"],
            "endpoint": LLM_CONFIG["endpoint"],
            "temperature": LLM_CONFIG["temperature"],
            "max_output_tokens": LLM_CONFIG["max_output_tokens"],
            "timeout_seconds": LLM_CONFIG["timeout_seconds"],
            "json_mode": LLM_CONFIG["json_mode"],
            "retry_policy": LLM_CONFIG["retry_policy"],
            "selection_budget": BUDGET_K,
            "seeds": SEEDS,
            "seed_semantics": ("one method-seed = one independent selection; the same seed list is used across "
                               "all three arms so paired differences share the identical candidate permutation "
                               "(ablation protocol sections 3/10)."),
            "candidate_order_permutations": permutations,
            "output_schema": OUTPUT_SCHEMA,
            "arm_prompts": arm_prompt_summary,
            "pool_sha256": pool_file_hashes,
            "snapshot_arm_view_sha256": {a: snap_manifest["snapshots"]["arm_views"][a]["sha256"]
                                         for a in ("blind", "generic", third_key)},
            "generic_rules_sha256": GENERIC_RULES_SHA,
            "status": "frozen_pre_registered_not_yet_executed",
        }
        rel_pm = f"artifacts/experiments/knowledge_ablation_prompts/{pname}/prompt_manifest.json"
        path_pm = EXPERIMENTS / f"knowledge_ablation_prompts/{pname}/prompt_manifest.json"
        planned_files.add(path_pm)
        if path_pm.exists():
            raise RuntimeError(f"FAIL-CLOSED: refusing to overwrite existing {rel_pm}")
        write_json(path_pm, prompt_manifest)
        file_hashes[rel_pm] = sha256_file(rel_pm)

        # ---- Finalize manifests for this project ----
        for rel_c, obj in (
            (f"artifacts/experiments/knowledge_ablation_snapshots/{pname}/project_commit_manifest.json", commit_manifest),
            (f"artifacts/experiments/knowledge_ablation_snapshots/{pname}/knowledge_snapshot_manifest.json", snap_manifest),
        ):
            path = EXPERIMENTS / "/".join(rel_c.split("/")[2:])
            planned_files.add(path)
            if path.exists():
                raise RuntimeError(f"FAIL-CLOSED: refusing to overwrite existing {rel_c}")
            write_json(path, obj)
            file_hashes[rel_c] = sha256_file(rel_c)

    # ---- Top-level manifest ----
    top = {
        "schema_version": 2,
        "purpose": "LLM knowledge-ablation Gate 0-2 generated artifact manifest (remediation v2, human review)",
        "protocol_sha256": protocol_sha,
        "remediation_v2_notes": [
            "Fix 1: LLM-generic is generic-rules-only (knowledge_ablation_generic_rules_v1.json).",
            "Fix 2: knowledge_snapshot_manifest full_pre/status read from live snapshot.",
            "Fix 3: all arm views/bundles/audits/manifests regenerated.",
            "Fix 4: leakage audit scans historical + current project terms + evidence markers.",
            "Fix 5: ESHOP third arm = LLM-partial-pre (full_pre not claimable); SOCIALNET = LLM-full-pre.",
            "Fix 6: 40/30 formal pools are NOT protocol-conformant formal-48 pools; requires amendment.",
            "Fix 7: candidate_id -> mutation_path mapping + YAML under knowledge_ablation_mutations/; pools untouched.",
        ],
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "status": "frozen_pending_human_review",
        "gates": {"gate0": "verified", "gate1": "frozen_pending_review", "gate2": "frozen_pending_review"},
        "leakage_audit_reviewer_decision": "pending_human_review",
        "pool_compositions": pool_compositions,
        "formal_pool_conformance": formal_conformance,
        "generic_rules": {"file": GENERIC_RULES_FILE, "sha256": GENERIC_RULES_SHA},
        "files": dict(sorted(file_hashes.items())),
    }
    rel_top = "artifacts/experiments/knowledge_ablation_manifest_gate0to2.json"
    path_top = EXPERIMENTS / "knowledge_ablation_manifest_gate0to2.json"
    planned_files.add(path_top)
    if path_top.exists():
        raise RuntimeError(f"FAIL-CLOSED: refusing to overwrite existing {rel_top}")
    write_json(path_top, top)
    file_hashes[rel_top] = sha256_file(rel_top)

    # Integrity check: every planned file exists and its recorded hash matches.
    missing = [str(f) for f in planned_files if not f.exists()]
    if missing:
        raise RuntimeError(f"planned files missing: {missing}")
    mismatched = [rel for rel, h in file_hashes.items() if h and sha256_file(rel) != h]
    if mismatched:
        raise RuntimeError(f"hash mismatch after write: {mismatched}")

    print(f"\nGenerated {len(file_hashes)} files under artifacts/experiments/knowledge_ablation_*")
    for rel, h in sorted(file_hashes.items()):
        print(f"  {h}  {rel}")
    print("\nPool compositions:")
    for key, comp in sorted(pool_compositions.items()):
        print(f"  {key}: {comp}")
    print("\nFormal conformance:")
    for key, fc in sorted(formal_conformance.items()):
        print(f"  {key}: actual={fc['pool_size_actual']} target={fc['pool_size_target']} "
              f"amendment_required={fc['requires_protocol_amendment']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
