"""Generate a sparse-ground-truth comparison registry over the 20-candidate pool.

M0 (random) and M1 (ChaosEater-adapter) draw from the full 20-candidate pool;
score-driven methods (M3/M4/A0-A4) sort by their static score and are limited
to the scored candidates (the extended candidates carry score 0, so they never
rank ahead). This makes the "scoring methods are blind to unknown candidates"
property explicit. M1 is filled by generate_m1_adapter_plans.py (--extended).
"""

from __future__ import annotations

import argparse
import json
import random
import time
from pathlib import Path
from typing import Any

from extended_candidate_pool import extended_candidate_pool
from generate_deep_comparison_matrix import METHODS, make_plan

ROOT = Path(__file__).resolve().parents[1]
EXECUTION_DIR = ROOT / "artifacts" / "experiments" / "execution"


def generate(replicate: int, seed: int, candidate_budget: int) -> dict[str, Any]:
    candidates = extended_candidate_pool()
    result: dict[str, Any] = {
        "schema_version": 1,
        "tool": "generate_extended_registry",
        "replicate": replicate,
        "seed": seed,
        "candidate_budget": candidate_budget,
        "candidate_universe": [item["candidate_id"] for item in candidates],
        "same_candidate_pool": True,
        "pool_note": (
            "20-candidate pool: 12 executed candidates + 8 unexecuted extended "
            "candidates (score 0). Score-driven methods are blind to score-0 candidates."
        ),
        "methods": [],
    }
    for method in METHODS:
        method_result = {key: value for key, value in method.items() if key not in {"score"}}
        method_result["plans"] = []
        if method["status"] != "available":
            result["methods"].append(method_result)
            continue
        if method["id"] == "M0":
            selected = random.Random(seed).sample(candidates, candidate_budget)
        elif method["id"] == "M1":
            # M1 is generated by the LLM adapter; leave blocked marker here.
            method_result["status"] = "blocked_external_reproduction"
            method_result["blocker"] = "filled by generate_m1_adapter_plans.py --extended"
            result["methods"].append(method_result)
            continue
        else:
            score_name = method.get("score", "local")
            selected = sorted(
                candidates, key=lambda item: (-item["scores"][score_name], item["candidate_id"])
            )[:candidate_budget]
        started = time.perf_counter()
        for rank, candidate in enumerate(selected, 1):
            elapsed_ms = int((time.perf_counter() - started) * 1000)
            method_result["plans"].append(make_plan(method, candidate, replicate, rank, elapsed_ms))
        result["methods"].append(method_result)
    return result


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--replicate", type=int, required=True)
    parser.add_argument("--seed", type=int, required=True)
    parser.add_argument("--candidate-budget", type=int, default=10)
    args = parser.parse_args()
    result = generate(args.replicate, args.seed, args.candidate_budget)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(result, indent=2, ensure_ascii=True) + "\n", encoding="utf-8")
    print(json.dumps({"output": str(args.output), "candidates": len(result["candidate_universe"])}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
